Gh0stBlade/KAIN2

KAIN2/Game/GLYPH.C, KAIN2/Game/PHYSICS.C
Updated Glyph.C and Physics.C
https://decomp.me/scratch/RC5Ol Glyph_EndFX 97%
https://decomp.me/scratch/FrlQz GlyphTrigger 98.57%
https://decomp.me/scratch/W6E6k MANA_Pickup 98.57%
https://decomp.me/scratch/Z8Una HUD_Init 96.07% - IDA code was not recognized so had to change the target dli     $v0, 0xFFFFFFFFFFFFFC18 to li     $v0, 0xFFFFFC18 and then it worked.
https://decomp.me/scratch/LlA6d HUD_Setup_Chit_Count 99.29%
https://decomp.me/scratch/EBAAK PhysicsCheckLOS 99.58% 
https://decomp.me/scratch/2CuVK PHYSICS_CheckLineInWorldMask 99.31%
=> Updated matching

KAIN2/Game/FX.C, KAIN2/Game/STREAM.C
STREAM_RemoveInstancesWithIDInInstanceList: Removed value assignment from declaration and changed conditional statements syntax to adhere to the code guideline.
FX_Die: Changed conditional statements syntax to adhere to the code guideline.
=> Code Fixing

KAIN2/Game/G2/ANMG2ILF.C
https://decomp.me/scratch/F1Ina
=> [ANMG2ILF]: Implement G2Anim_SetPaused

KAIN2/Game/MATH3D.C
https://decomp.me/scratch/VvFBo
=> [MATH3D]: Implement MATH3D_LengthXYZ

KAIN2/Game/RAZIEL/RAZIEL.C
Matching - 99.36%
https://decomp.me/scratch/WjekB
Original matching percentage was 60.65%
=> [RAZIEL]: Update StateHandlerCompression

KAIN2/Game/RAZIEL/RAZIEL.C
Matching - 99.23%
https://decomp.me/scratch/p3zQD
Current codebase version matching percentage is 44.68%.
=> [RAZIEL]: Update StateHandlerFall

KAIN2/Game/DEBUG.C
Matching - 97.88%
https://decomp.me/scratch/OyGoL
=> [DEBUG]: Implement DEBUG_FogLoad

KAIN2/Game/RAZIEL/RAZIEL.C
Matching - 99.61%
https://decomp.me/scratch/YPiJX
Current codebase version matching percentage is 58.56%.
=> [RAZIEL]: Update StateHandlerSoulSuck

KAIN2/Game/RAZIEL/RAZIEL.C
Matching - 99.65%
https://decomp.me/scratch/jUU2Q
Current codebase version matching percentage is 78.67%.
=> [RAZIEL]: Update StateHandlerStartTurn

KAIN2/Game/RAZIEL/RAZIEL.C
Matching - 99.48%
https://decomp.me/scratch/nkpDf
Current codebase version matching percentage is 31.61%.
=> [RAZIEL]: Update StateHandlerIdle

KAIN2/Game/RAZIEL/RAZIEL.C
Matching - 99.23%
https://decomp.me/scratch/RtAml
Current codebase version matching percentage is 32.26%.
=> [RAZIEL]: Update StateHandlerStartMove

KAIN2/Game/RAZIEL/RAZIEL.C
Matching - 99.71%
https://decomp.me/scratch/wNfv6
Current codebase version matching percentage is 55.76%.
=> [RAZIEL]: Update StateHandlerStopMove

KAIN2/Game/RAZIEL/RAZIEL.C
Matching - 99.54%
https://decomp.me/scratch/QAuCG
Current codebase version matching percentage is 35.59%.
=> [RAZIEL]: Update StateHandlerMove

KAIN2/Game/RAZIEL/RAZIEL.C
Matching - 98.94%
https://decomp.me/scratch/3ROX2
Current codebase version matching percentage is 61.96%.
=> [RAZIEL]: Update StateHandlerJump

KAIN2/Game/RAZIEL/RAZIEL.C
Matching - 98.14%
https://decomp.me/scratch/UWeF7
Current codebase version matching percentage is 13.26%.
=> [RAZIEL]: Update DefaultStateHandler

KAIN2/Game/MONSTER/MONSTER.C
Matching - 99.93%
https://decomp.me/scratch/ju9mZ
=> [MONSTER]: Update MON_CleanUp

KAIN2/Game/MONSTER/MONMSG.C
https://decomp.me/scratch/PeZg6
=> [MONMSG]: Update MON_GroundMoveQueueHandler

KAIN2/Game/MONSTER/MONAPI.C
https://decomp.me/scratch/GLYBS
=> [MONAPI]: Update MonsterProcess

KAIN2/Game/INSTANCE.C
https://decomp.me/scratch/2qYcB
=> [INSTANCE]: Update INSTANCE_Deactivate

KAIN2/Game/CAMERA.C
Matching - 99.37%
https://decomp.me/scratch/6Azid
=> [CAMERA]: Implement CAMERA_SphereToSphereWithLines

KAIN2/Game/MONSTER/SOUL.C
https://decomp.me/scratch/hkKIi
=> [SOUL]: Update SOUL_WanderEntry

KAIN2/Game/MONSTER/SOUL.C
Matching - 99.81%
https://decomp.me/scratch/S5blq
=> [SOUL]: Update SOUL_Birth

KAIN2/Game/MONSTER/SOUL.C
https://decomp.me/scratch/9LNwF
=> [SOUL]: Update SOUL_MoveToDest

KAIN2/Game/MONSTER/SOUL.C
https://decomp.me/scratch/Qcu7z
=> [SOUL]: Update SOUL_Fade

KAIN2/Game/MONSTER/SOUL.C
https://decomp.me/scratch/q90n6
=> [SOUL]: Update SOUL_Physics

KAIN2/Game/MONSTER/SOUL.C
https://decomp.me/scratch/6QJLP
=> [SOUL]: Update SOUL_QueueHandler

KAIN2/Game/MONSTER/SOUL.C
https://decomp.me/scratch/Xs2Cd
=> [SOUL]: Update SOUL_Init

KAIN2/Game/MONSTER/SOUL.C
https://decomp.me/scratch/YybVh
=> [SOUL]: Update SOUL_IdleEntry

KAIN2/Game/MONSTER/SOUL.C
Matching - 99.95%
https://decomp.me/scratch/xCncK
=> [SOUL]: Update SOUL_Wander

KAIN2/Game/MONSTER/SOUL.C
https://decomp.me/scratch/cB6Xv
=> [SOUL]: Update SOUL_Reanimate

KAIN2/Game/MONSTER/SOUL.C
Matching - 99.92%
https://decomp.me/scratch/16Qg4
=> [SOUL]: Update SOUL_Idle

KAIN2/Game/MONSTER/SOUL.C
https://decomp.me/scratch/G3yij
=> [SOUL]: Update SOUL_ReanimateEntry

KAIN2/Game/PHYSICS.C
https://decomp.me/scratch/rZ18K
=> [PHYSICS]: Update PHYSICS_CheckFaceStick

KAIN2/Game/GENERIC.C
https://decomp.me/scratch/Y79OF
=> [GENERIC]: Update GenericQuery

KAIN2/Game/PHYSICS.C
https://decomp.me/scratch/q8Cdl
Current codebase version matching percentage is 55%.
=> [PHYSICS]: Update PHYSICS_FindVFromAAndD

KAIN2/Game/PHYSICS.C
https://decomp.me/scratch/qQPRC
=> [PHYSICS]: Update PHYSICS_StopIfCloseToTarget

KAIN2/Game/PHYSICS.C
https://decomp.me/scratch/9YdBj
Current codebase version matching percentage is 50%.
=> [PHYSICS]: Update PHYSICS_CheckForTerrainCollide

KAIN2/Game/PHYSICS.C
https://decomp.me/scratch/TdrJy
Current codebase version matching percentage is 76.47%.
=> [PHYSICS]: Update PHYSICS_CheckForObjectCollide

KAIN2/Game/PHYSICS.C
https://decomp.me/scratch/30mTd
=> [PHYSICS]: Update PHYSICS_CheckForValidMove

KAIN2/Game/PHYSICS.C
https://decomp.me/scratch/4ptHF
=> [PHYSICS]: Update PHYSICS_GenericLineCheck

KAIN2/Game/PHYSICS.C
https://decomp.me/scratch/jbcib
Current codebase version matching percentage is 83.06%.
=> [PHYSICS]: Update SetNoPtCollideInFamily

KAIN2/Game/PHYSICS.C
https://decomp.me/scratch/rOFN3
=> [PHYSICS]: Update ResetNoPtCollideInFamily

KAIN2/Game/PHYSICS.C
https://decomp.me/scratch/OnrYY
=> [PHYSICS]: Update PHYSICS_CheckLineInWorld

KAIN2/Game/PHYSICS.C
https://decomp.me/scratch/3Sv6b
=> [PHYSICS]: Update PHYSICS_CheckLineInWorldMask

KAIN2/Game/PHYSICS.C
https://decomp.me/scratch/8jmpQ
=> [PHYSICS]: Update PhysicsDefaultLinkedMoveResponse

KAIN2/Game/PHYSICS.C
https://decomp.me/scratch/PdcRJ
Current codebase version matching percentage is 86%.
=> [PHYSICS]: Update PHYSICS_FindAFromDAndT

KAIN2/Game/PHYSICS.C
https://decomp.me/scratch/EEdIB
=> [PHYSICS]: Update PhysicsMoveLocalZClamp

KAIN2/Game/PHYSICS.C
https://decomp.me/scratch/jOT55
=> [PHYSICS]: Update PhysicsUpdateTface

KAIN2/Game/PHYSICS.C
https://decomp.me/scratch/RGDN6
=> [PHYSICS]: Update PhysicsDefaultGravityResponse

KAIN2/Game/PHYSICS.C
https://decomp.me/scratch/ZY4D5
=> [PHYSICS]: Update PhysicsCheckLOS

KAIN2/Game/PHYSICS.C
https://decomp.me/scratch/HKZon
=> [PHYSICS]: Update PHYSICS_GenericLineCheckSetup

KAIN2/Game/PHYSICS.C
https://decomp.me/scratch/cTkPZ
=> [PHYSICS]: Update PhysicsFollowWall

KAIN2/Game/COLLIDE.C
https://decomp.me/scratch/28LbI
=> [COLLIDE]: Update COLLIDE_SetBSPTreeFlag

KAIN2/Game/COLLIDE.C
https://decomp.me/scratch/k6k6t
=> [COLLIDE]: Update COLLIDE_GetBSPTreeFlag

KAIN2/Game/COLLIDE.C
https://decomp.me/scratch/kUOK7
=> [COLLIDE]: Update COLLIDE_InstanceListWithSignals

KAIN2/Game/COLLIDE.C
https://decomp.me/scratch/Gq5Zn
=> [COLLIDE]: Update COLLIDE_InstanceTerrain

KAIN2/Game/LIGHT3D.C
https://decomp.me/scratch/nlwbT
=> [LIGHT3D]: Update LIGHT_SetAmbientInstance

KAIN2/Game/LIGHT3D.C
https://decomp.me/scratch/9tEjr
=> [LIGHT3D]: Update LIGHT_GetAmbient

KAIN2/Game/GLYPH.C
https://decomp.me/scratch/mCgY9
=> [GLYPH]: Update HUD_Damp

KAIN2/Game/GLYPH.C
https://decomp.me/scratch/i5nqv
=> [GLYPH]: Update HUD_Init

KAIN2/Game/GLYPH.C
https://decomp.me/scratch/I1xNP
=> [GLYPH]: Update HUD_Setup_Chit_Count

KAIN2/Game/GLYPH.C
https://decomp.me/scratch/qaIMc
=> [GLYPH]: Update HUD_Update

KAIN2/Game/GLYPH.C
Matching - 99.58%
https://decomp.me/scratch/bPtpC
=> [GLYPH]: Update HUD_GetPlayerScreenPt

KAIN2/Game/LIGHT3D.C
https://decomp.me/scratch/TtLQo
=> [LIGHT3D]: Update LIGHT_CalcDQPTable

KAIN2/Game/LIGHT3D.C
https://decomp.me/scratch/dx1nx
=> [LIGHT3D]: Update LIGHT_CalcShadowPositions

KAIN2/Game/COLLIDE.C
https://decomp.me/scratch/kYB5J
=> [COLLIDE]: Update COLLIDE_InstanceList

KAIN2/Game/COLLIDE.C
https://decomp.me/scratch/oPJW3
=> [COLLIDE]: Update COLLIDE_SegmentCollisionOff

KAIN2/Game/COLLIDE.C
https://decomp.me/scratch/9nL0p
=> [COLLIDE]: Update COLLIDE_InstanceListTerrain

KAIN2/Game/COLLIDE.C
https://decomp.me/scratch/dnjXY
=> [COLLIDE]: Update COLLIDE_SegmentCollisionOn

KAIN2/Game/COLLIDE.C
https://decomp.me/scratch/X2z2X
=> [COLLIDE]: Update COLLIDE_SphereAndTerrain

KAIN2/Game/COLLIDE.C
https://decomp.me/scratch/EImAQ
=> [COLLIDE]: Update COLLIDE_PointAndWorld

KAIN2/Game/FX.C
https://decomp.me/scratch/clxti
=> [FX]: Update FX_StartInstanceEffect

KAIN2/Game/RAZIEL/RAZIEL.C
https://decomp.me/scratch/LrPp2
=> [RAZIEL]: Update ProcessTimers

KAIN2/Game/COLLIDE.C
https://decomp.me/scratch/JZl6x
=> [COLLIDE]: Update COLLIDE_InstanceTerrainSignal

KAIN2/Game/PHYSOBS.C
https://decomp.me/scratch/wB2Vi
=> [PHYSOBS]: Update InitPhysicalObject

KAIN2/Game/LIGHT3D.C
https://decomp.me/scratch/fGx59
=> [LIGHT3D]: Update LIGHT_SetMatrixForLightGroupInstance

KAIN2/Game/VRAM.C, KAIN2/Game/VRAM.H
https://decomp.me/scratch/N0MP4
=> [VRAM]: Implement VRAM_RearrangeVramsLayer

KAIN2/Game/COLLIDE.C
https://decomp.me/scratch/pIAYr
=> [COLLIDE]: Update COLLIDE_PointAndTerrain

KAIN2/Game/COLLIDE.C
https://decomp.me/scratch/F97Fj
=> [COLLIDE]: Update COLLIDE_PointInTriangle2DPub

KAIN2/Game/COLLIDE.C
https://decomp.me/scratch/UP9hZ
=> [COLLIDE]: Update COLLIDE_GetNormal

KAIN2/Game/COLLIDE.C
https://decomp.me/scratch/HoWHu
=> [COLLIDE]: Update COLLIDE_IntersectLineAndBox

KAIN2/Game/COLLIDE.C
https://decomp.me/scratch/45z2S
=> [COLLIDE]: Update COLLIDE_WithinXYBounds

KAIN2/Game/COLLIDE.C
https://decomp.me/scratch/kd5Z6
=> [COLLIDE]: Update COLLIDE_WithinXZBounds

KAIN2/Game/COLLIDE.C
https://decomp.me/scratch/aL0RQ
=> [COLLIDE]: Update COLLIDE_WithinYZBounds

KAIN2/Game/PHYSICS.C
https://decomp.me/scratch/n579b
=> [PHYSICS]: Update PhysicsDefaultCheckSwimResponse

KAIN2/Game/PHYSICS.C
https://decomp.me/scratch/Ugagw
=> [PHYSICS]: Update PhysicsCheckSwim

KAIN2/Game/PHYSICS.C
https://decomp.me/scratch/EKsrc
=> [PHYSICS]: Update PhysicsCheckDropOff

KAIN2/Game/PLAN/PLANPOOL.C
Matching - 99.85%
https://decomp.me/scratch/AJYdL
=> [PLANCOLL]: Update PLANPOOL_GetClosestUnexploredValidNeighbor

KAIN2/Game/PHYSICS.C
https://decomp.me/scratch/otyl9
=> [PHYSICS]: Update PhysicsCheckBlockers

KAIN2/Game/PHYSICS.C
https://decomp.me/scratch/hY5q2
=> [PHYSICS]: Update PhysicsMove

KAIN2/Game/LIGHT3D.C
https://decomp.me/scratch/nJl50
=> [LIGHT3D]: Update LIGHT_PresetInstanceLight

KAIN2/Game/PHYSICS.C
https://decomp.me/scratch/u1W1c
=> [PHYSICS]: Update PhysicsCheckGravity

KAIN2/Game/LIGHT3D.C
https://decomp.me/scratch/pJ6Cf
=> [LIGHT3D]: Update LIGHT_GetLightMatrix

KAIN2/Game/INSTANCE.C
https://decomp.me/scratch/GyFKq
=> [INSTANCE]: Update INSTANCE_Reactivate

KAIN2/Game/INSTANCE.C
https://decomp.me/scratch/bu0UB
=> [INSTANCE]: Update INSTANCE_ForceActive

KAIN2/Game/INSTANCE.C
Matching - 99.62%
https://decomp.me/scratch/OEfce
=> [INSTANCE]: Update INSTANCE_DeactivateFarInstances

KAIN2/Game/INSTANCE.C
https://decomp.me/scratch/3Me7x
=> [INSTANCE]: Update INSTANCE_InitInstanceList

KAIN2/Game/INSTANCE.C
https://decomp.me/scratch/NDQse
=> [INSTANCE]: Update INSTANCE_NewInstance

KAIN2/Game/INSTANCE.C
https://decomp.me/scratch/MCupw
=> [INSTANCE]: Update INSTANCE_InstanceGroupNumber

KAIN2/Game/INSTANCE.C
https://decomp.me/scratch/Gh3mW
=> [INSTANCE]: Update INSTANCE_InsertInstanceGroup

KAIN2/Game/INSTANCE.C
https://decomp.me/scratch/5efzt
=> [INSTANCE]: Update INSTANCE_ReallyRemoveInstance

KAIN2/Game/INSTANCE.C
https://decomp.me/scratch/MWezU
=> [INSTANCE]: Update INSTANCE_CleanUpInstanceList

KAIN2/Game/INSTANCE.C
https://decomp.me/scratch/hGVmK
=> [INSTANCE]: Update INSTANCE_Introduced

KAIN2/Game/INSTANCE.C
https://decomp.me/scratch/wAQz5
=> [INSTANCE]: Update INSTANCE_GetIntroCommand

KAIN2/Game/INSTANCE.C
https://decomp.me/scratch/jGUTT
=> [INSTANCE]: Update INSTANCE_FindIntroCommand

KAIN2/Game/INSTANCE.C
https://decomp.me/scratch/ueddK
=> [INSTANCE]: Update INSTANCE_InitEffects

KAIN2/Game/INSTANCE.C
https://decomp.me/scratch/nnZzV
=> [INSTANCE]: Update INSTANCE_GetSplineFrameNumber

KAIN2/Game/INSTANCE.C
https://decomp.me/scratch/sRXO0
=> [INSTANCE]: Update INSTANCE_IntroduceInstance

KAIN2/Game/INSTANCE.C
https://decomp.me/scratch/Su14T
=> [INSTANCE]: Update INSTANCE_DefaultInit

KAIN2/Game/INSTANCE.C
https://decomp.me/scratch/CAR7G
=> [INSTANCE]: Update INSTANCE_KillInstance

KAIN2/Game/INSTANCE.C
https://decomp.me/scratch/nrDI9
=> [INSTANCE]: Update INSTANCE_Query

KAIN2/Game/INSTANCE.C
https://decomp.me/scratch/fGCLd
=> [INSTANCE]: Update INSTANCE_AdditionalCollideFunctions

KAIN2/Game/INSTANCE.C
https://decomp.me/scratch/UW3h4
=> [INSTANCE]: Update INSTANCE_LinkToParent

KAIN2/Game/INSTANCE.C
https://decomp.me/scratch/XkFpk
=> [INSTANCE]: Update INSTANCE_SetStatsData

KAIN2/Game/INSTANCE.C
https://decomp.me/scratch/3V68I
=> [INSTANCE]: Update INSTANCE_SpatialRelationships

KAIN2/Game/INSTANCE.C
https://decomp.me/scratch/hFbsc
=> [INSTANCE]: Update INSTANCE_Find

KAIN2/Game/INSTANCE.C
https://decomp.me/scratch/vde9q
=> [INSTANCE]: Update INSTANCE_FindWithID

KAIN2/Game/INSTANCE.C
https://decomp.me/scratch/Kt3O1
=> [INSTANCE]: Update INSTANCE_Broadcast

KAIN2/Game/INSTANCE.C
https://decomp.me/scratch/xEcdM
=> [INSTANCE]: Update INSTANCE_Post

KAIN2/Game/INSTANCE.C
https://decomp.me/scratch/fRUYZ
=> [INSTANCE]: Update INSTANCE_DefaultAnimCallback

KAIN2/Game/INSTANCE.C
https://decomp.me/scratch/3kGwH
=> [INSTANCE]: Update INSTANCE_BirthObject

KAIN2/Game/INSTANCE.C
https://decomp.me/scratch/LGU2W
=> [INSTANCE]: Update INSTANCE_UpdateFamilyStreamUnitID

KAIN2/Game/INSTANCE.C
https://decomp.me/scratch/NncVG
=> [INSTANCE]: Update INSTANCE_ReallyRemoveAllChildren

KAIN2/Game/INSTANCE.C
https://decomp.me/scratch/4KYxH
=> [INSTANCE]: Update INSTANCE_GetFadeValue

KAIN2/Game/INSTANCE.C
https://decomp.me/scratch/UEKCW
=> [INSTANCE]: Update INSTANCE_GetChildLinkedToSegment

KAIN2/Game/EVENT.C
https://decomp.me/scratch/doOse
=> [EVENT]: Update EVENT_ResetAllOneTimeVariables

KAIN2/Game/EVENT.C
https://decomp.me/scratch/Jq5xc
=> [EVENT]: Update EVENT_AddSignalToReset

KAIN2/Game/EVENT.C
https://decomp.me/scratch/ea82T
=> [EVENT]: Update HINT_ResetHint

KAIN2/Game/EVENT.C
https://decomp.me/scratch/0aVWB
=> [EVENT]: Update HINT_StartHint

KAIN2/Game/EVENT.C
https://decomp.me/scratch/8zTWj
=> [EVENT]: Update HINT_KillSpecificHint

KAIN2/Game/EVENT.C
https://decomp.me/scratch/wVR5J
=> [EVENT]: Update HINT_GetCurrentHint

KAIN2/Game/EVENT.C
https://decomp.me/scratch/N6vsf
=> [EVENT]: Update EVENT_ProcessTimers

KAIN2/Game/EVENT.C
https://decomp.me/scratch/0WoOQ
=> [EVENT]: Update EVENT_ProcessHints

KAIN2/Game/EVENT.H
Update structs to match current game build being decompilated.
=> [EVENT]: Update structs

KAIN2/Game/EVENT.C
https://decomp.me/scratch/AFtuf
=> [EVENT]: Update EVENT_RemoveTimer

KAIN2/Game/EVENT.C
https://decomp.me/scratch/O517y
=> [EVENT]: Update EVENT_InitTimers

KAIN2/Game/EVENT.C
https://decomp.me/scratch/DmcoM
=> [EVENT]: Update EVENT_InitTerrainMovement

KAIN2/Game/EVENT.C
https://decomp.me/scratch/pzIMP
=> [EVENT]: Update EVENT_Init

KAIN2/Game/EVENT.C
https://decomp.me/scratch/YYHTt
=> [EVENT]: Update EVENT_GetNextTerrainMove

KAIN2/Game/EVENT.C
https://decomp.me/scratch/0sp2F
=> [EVENT]: Update EVENT_ProcessMovingWater

KAIN2/Game/EVENT.C
https://decomp.me/scratch/PIG1t
=> [EVENT]: Update EVENT_DoProcess

KAIN2/Game/EVENT.C
https://decomp.me/scratch/WQMHO
=> [EVENT]: Update EVENT_GetNextTimer

KAIN2/Game/EVENT.C
https://decomp.me/scratch/Nwx8q
=> [EVENT]: Update EVENT_Process

KAIN2/Game/EVENT.C
https://decomp.me/scratch/acdOA
=> [EVENT]: Update EVENT_BSPProcess

KAIN2/Game/EVENT.C
https://decomp.me/scratch/9rYUR
=> [EVENT]: Update EVENT_ProcessEvents

KAIN2/Game/EVENT.C
https://decomp.me/scratch/QEaKj
=> [EVENT]: Update EVENT_DoAction

KAIN2/Game/EVENT.C
https://decomp.me/scratch/vzO6C
=> [EVENT]: Update EVENT_IsConditionTrue

KAIN2/Game/EVENT.C
https://decomp.me/scratch/xWJxx
=> [EVENT]: Update EVENT_ResolveObjectIntro

KAIN2/Game/EVENT.C
https://decomp.me/scratch/IbDfq
=> [EVENT]: Update EVENT_AddPlayerObjectToStack

KAIN2/Game/EVENT.C
https://decomp.me/scratch/jGrnL
=> [EVENT]: Update EVENT_ChangeOperandToNumber

KAIN2/Game/EVENT.C
https://decomp.me/scratch/40jeq
=> [EVENT]: Update EVENT_AddSubListObjectToStack

KAIN2/Game/EVENT.C
https://decomp.me/scratch/NTBk5
=> [EVENT]: Update EVENT_TransformRotation3dAttribute

KAIN2/Game/EVENT.C
https://decomp.me/scratch/HC9Rq
=> [EVENT]: Update EVENT_ModifyObjectToStackWithAttribute

KAIN2/Game/EVENT.C
https://decomp.me/scratch/X1WZG
=> [EVENT]: Update EVENT_GetSoundValue

KAIN2/Game/EVENT.C
https://decomp.me/scratch/868ga
=> [EVENT]: Update EVENT_GetSplineFrameNumber

KAIN2/Game/EVENT.C
https://decomp.me/scratch/pkDf3
=> [EVENT]: Update EVENT_CreateSaveEvent

KAIN2/Game/EVENT.C
https://decomp.me/scratch/YcaIc
=> [EVENT]: Update EVENT_AddInstanceToInstanceList

KAIN2/Game/STREAM.C
https://decomp.me/scratch/wzThA
=> [STREAM]: Update STREAM_FillOutFileNames

KAIN2/Game/STREAM.C
https://decomp.me/scratch/ONyYU
=> [STREAM]: Update STREAM_AbortAreaLoad

KAIN2/Game/STREAM.C
https://decomp.me/scratch/piVfD
=> [STREAM]: Update STREAM_Init

KAIN2/Game/STREAM.C
https://decomp.me/scratch/mktDd
=> [STREAM]: Update FindObjectName

KAIN2/Game/STREAM.C
https://decomp.me/scratch/NVjtN
=> [STREAM]: Update FindObjectInTracker

KAIN2/Game/STREAM.C
https://decomp.me/scratch/OQKNh
=> [STREAM]: Update FindStreamUnitFromLevel

KAIN2/Game/STREAM.C
https://decomp.me/scratch/M4Ixs
=> [STREAM]: Update STREAM_LoadObjectReturn

KAIN2/Game/STREAM.C
https://decomp.me/scratch/iUAG6
=> [STREAM]: Update STREAM_InList

KAIN2/Game/STREAM.C
https://decomp.me/scratch/DXs2S
=> [STREAM]: Update STREAM_DumpSomeMonsters

KAIN2/Game/STREAM.C
https://decomp.me/scratch/DT3B9
=> [STREAM]: Update STREAM_NoMonsters

KAIN2/Game/STREAM.C
https://decomp.me/scratch/NxkJ9
=> [STREAM]: Update STREAM_YesMonsters

KAIN2/Game/STREAM.C
https://decomp.me/scratch/uTEM3
=> [STREAM]: Update STREAM_TryAndDumpANonResidentObject

KAIN2/Game/STREAM.C
https://decomp.me/scratch/oVkmo
=> [STREAM]: Update InsertGlobalObject

KAIN2/Game/STREAM.C
https://decomp.me/scratch/NklHR
=> [STREAM]: Update STREAM_GetObjectTracker

KAIN2/Game/STREAM.C
https://decomp.me/scratch/yRhiX
=> [STREAM]: Update LoadLevelObjects

KAIN2/Game/STREAM.C
https://decomp.me/scratch/abmV7
=> [STREAM]: Update STREAM_IsAnInstanceUsingObject

KAIN2/Game/STREAM.C
https://decomp.me/scratch/kwiyh
=> [STREAM]: Update STREAM_StreamLoadObjectAbort

KAIN2/Game/STREAM.C
https://decomp.me/scratch/85VYl
=> [STREAM]: Update STREAM_DumpLoadingObjects

KAIN2/Game/STREAM.C
https://decomp.me/scratch/X4qFh
=> [STREAM]: Update STREAM_DumpObject

KAIN2/Game/STREAM.C
https://decomp.me/scratch/LOfKp
=> [STREAM]: Update STREAM_IsObjectInAnyUnit

KAIN2/Game/STREAM.C
https://decomp.me/scratch/ijro7
=> [STREAM]: Update STREAM_RemoveAllObjectsNotInUse

KAIN2/Game/STREAM.C
https://decomp.me/scratch/rLADR
=> [STREAM]: Update RemoveAllObjects

KAIN2/Game/STREAM.C
https://decomp.me/scratch/e2Wto
=> [STREAM]: Update STREAM_GetLevelWithID

KAIN2/Game/STREAM.C
https://decomp.me/scratch/NAFm7
=> [STREAM]: Update STREAM_GetStreamUnitWithID

KAIN2/Game/STREAM.C
https://decomp.me/scratch/5Xdel
=> [STREAM]: Update STREAM_IsMorphInProgress

KAIN2/Game/STREAM.C
https://decomp.me/scratch/4YvXO
=> [STREAM]: Update STREAM_SetMainFog

KAIN2/Game/STREAM.C
https://decomp.me/scratch/gntHE
=> [STREAM]: Update STREAM_SetStreamFog

KAIN2/Game/STREAM.C
https://decomp.me/scratch/x4CuT
=> [STREAM]: Update STREAM_GetWaterZLevel

KAIN2/Game/STREAM.C
https://decomp.me/scratch/hvBBW
=> [STREAM]: Update STREAM_StreamLoadLevelAbort

KAIN2/Game/STREAM.C
https://decomp.me/scratch/R1S0X
=> [STREAM]: Update STREAM_DoObjectLoadAndDump

KAIN2/Game/STREAM.C
https://decomp.me/scratch/PeG9I
=> [STREAM]: Update STREAM_LoadLevelReturn

KAIN2/Game/STREAM.C
https://decomp.me/scratch/Xnztz
=> [STREAM]: Update STREAM_UpdateInstanceCollisionInfo

KAIN2/Game/STREAM.C
https://decomp.me/scratch/Q8TJm
=> [STREAM]: Update STREAM_LoadMainVram

KAIN2/Game/STREAM.C
https://decomp.me/scratch/zkPHv
=> [STREAM]: Update STREAM_MoveIntoNewStreamUnit

KAIN2/Game/STREAM.C
https://decomp.me/scratch/ywdWF
=> [STREAM]: Update STREAM_LoadLevel

KAIN2/Game/STREAM.C
https://decomp.me/scratch/crsRc
=> [STREAM]: Update RemoveIntroducedLights

KAIN2/Game/STREAM.C
https://decomp.me/scratch/xW8kQ
=> [STREAM]: Update STREAM_RemoveInstancesWithIDInInstanceList

KAIN2/Game/STREAM.C
https://decomp.me/scratch/qI0oo
=> [STREAM]: Update STREAM_MarkUnitNeeded

KAIN2/Game/STREAM.C
https://decomp.me/scratch/xxley
=> [STREAM]: Update STREAM_DumpAllUnitsNotNeeded

KAIN2/Game/STREAM.C
https://decomp.me/scratch/Jrah4
=> [STREAM]: Update STREAM_DumpAllLevels

KAIN2/Game/STREAM.C
https://decomp.me/scratch/gSKHm
=> [STREAM]: Update STREAM_StreamLoadLevelReturn

KAIN2/Game/COLLIDE.C
https://decomp.me/scratch/v2T7V
=> [COLLIDE]: Update COLLIDE_CameraWithStreamSignals

KAIN2/Game/EVENT.C
https://decomp.me/scratch/yu8jM
=> [EVENT]: Update EVENT_ParseOpcode

KAIN2/Game/PHYSICS.C
https://decomp.me/scratch/tw3So
=> [PHYSICS]: Update PhysicsCheckEdgeGrabbing

KAIN2/Game/STREAM.C
https://decomp.me/scratch/ovJHs
=> [STREAM]: Update STREAM_LoadCurrentWarpRoom

KAIN2/Game/STREAM.C
https://decomp.me/scratch/oRuDh
=> [STREAM]: Update WARPGATE_RelocateLoadedWarpRooms

KAIN2/Game/STREAM.C
https://decomp.me/scratch/h7CD4
=> [STREAM]: Update WARPGATE_GetWarpRoomIndex

KAIN2/Game/STREAM.C
https://decomp.me/scratch/NcRYP
=> [STREAM]: Update WARPGATE_UpdateAddToArray

KAIN2/Game/STREAM.C
https://decomp.me/scratch/jolRE
=> [STREAM]: Update WARPGATE_RemoveFromArray

KAIN2/Game/STREAM.C
https://decomp.me/scratch/PYhOo
=> [STREAM]: Update WARPGATE_Init

KAIN2/Game/STREAM.C
https://decomp.me/scratch/rkoNd
=> [STREAM]: Update WARPGATE_EndUsingWarpgate

KAIN2/Game/STREAM.C
https://decomp.me/scratch/47fqG
=> [STREAM]: Update WARPGATE_IsWarpgateInUse

KAIN2/Game/STREAM.C
https://decomp.me/scratch/I7nl1
=> [STREAM]: Update WARPGATE_IsWarpgateActive

KAIN2/Game/STREAM.C
https://decomp.me/scratch/kG9ud
=> [STREAM]: Update STREAM_MarkWarpUnitsNeeded

KAIN2/Game/STREAM.C
https://decomp.me/scratch/2FAF6
=> [STREAM]: Update WARPGATE_IsWarpgateUsable

KAIN2/Game/STREAM.C
https://decomp.me/scratch/XInGU
=> [STREAM]: Update WARPGATE_IsWarpgateReady

KAIN2/Game/STREAM.C
https://decomp.me/scratch/mem3a
=> [STREAM]: Update WARPGATE_IsObjectOnWarpSide

KAIN2/Game/STREAM.C
https://decomp.me/scratch/9R2VU
=> [STREAM]: Update WARPGATE_IsWarpgateSpectral

KAIN2/Game/MONSTER/MONSENSE.C
https://decomp.me/scratch/23BhI
=> [MONSENSE]: Update MONSENSE_GetDistanceInDirection

KAIN2/Game/MONSTER/MONSENSE.C
https://decomp.me/scratch/5zJE0
=> [MONSENSE]: Update MONSENSE_InitIRList

KAIN2/Game/MONSTER/MONSENSE.C
https://decomp.me/scratch/PsJRe
=> [MONSENSE]: Update MONSENSE_Smell

KAIN2/Game/MONSTER/MONMSG.C
https://decomp.me/scratch/uqbje
=> [MONMSG]: Update MON_PupateQueueHandler

KAIN2/Game/MONSTER/MONMSG.C
https://decomp.me/scratch/oUYMo
=> [MONMSG]: Update MON_IdleQueueHandler

KAIN2/Game/MONSTER/MONMSG.C
https://decomp.me/scratch/ggLRb
=> [MONMSG]: Update MON_DefaultQueueHandler

KAIN2/Game/MONSTER/VWRAITH.C
https://decomp.me/scratch/OEtK6
=> [VWRAITH]: Update VWRAITH_CombatEntry

KAIN2/Game/MONSTER/VWRAITH.C
https://decomp.me/scratch/ziv0o
=> [VWRAITH]: Update VWRAITH_EmbraceEntry

KAIN2/Game/MONSTER/VWRAITH.C
https://decomp.me/scratch/B3DlM
=> [VWRAITH]: Update VWRAITH_Embrace

KAIN2/Game/MONSTER/HUMAN.C
https://decomp.me/scratch/TK7Lh
=> [HUMAN]: Update HUMAN_CleanUp

KAIN2/Game/MONSTER/MISSILE.C
https://decomp.me/scratch/E6YNa
=> [MISSILE]: Update MISSILE_Process

KAIN2/Game/MONSTER/MISSILE.C
https://decomp.me/scratch/4OG46
=> [MISSILE]: Update MISSILE_Collide

KAIN2/Game/MONSTER/MISSILE.C
https://decomp.me/scratch/tjnj2
=> [MISSILE]: Update MISSILE_FireAtInstance

KAIN2/Game/MONSTER/MONSENSE.C
https://decomp.me/scratch/cFwnU
=> [MONSENSE]: Update MONSENSE_GetMonsterIR

KAIN2/Game/MONSTER/MONAPI.C
https://decomp.me/scratch/0U3cy
=> [MONAPI]: Update MonsterAdditionalCollide

KAIN2/Game/MONSTER/MONAPI.C
https://decomp.me/scratch/EGm8y
=> [MONAPI]: Update MONAPI_SetLookAround

KAIN2/Game/MONSTER/MONAPI.C
https://decomp.me/scratch/5sXpa
=> [MONAPI]: Update MONAPI_ResetLookAround

KAIN2/Game/MONSTER/MONAPI.C
https://decomp.me/scratch/572y8
=> [MONAPI]: Update MONAPI_OkToLookAround

KAIN2/Game/MONSTER/MONAPI.C
https://decomp.me/scratch/I7JzI
=> [MONAPI]: Update MONAPI_DeleteRegen

KAIN2/Game/MONSTER/MONAPI.C
Matching - 99.31%
https://decomp.me/scratch/ZFqbo
=> [MONAPI]: Update MONAPI_ProcessGenerator

KAIN2/Game/MONSTER/MONAPI.C
https://decomp.me/scratch/l3EVF
=> [MONAPI]: Update AnimDistanceAndVel

KAIN2/Game/MONSTER/MONAPI.C
https://decomp.me/scratch/kEwBY
=> [MONAPI]: Update MonsterTranslateAnim

KAIN2/Game/MONSTER/MONSENSE.C
https://decomp.me/scratch/x3ng6
=> [MONSENSE]: Update MONSENSE_FindIR

KAIN2/Game/STREAM.C
https://decomp.me/scratch/OWbJG
=> [STREAM]: Update WARPGATE_IsUnitWarpRoom

KAIN2/Game/STREAM.C
https://decomp.me/scratch/yk1Kv
=> [STREAM]: Update RelocatePlanMarkers

KAIN2/Game/STREAM.C
https://decomp.me/scratch/hAYxC
=> [STREAM]: Update RelocateSFXMarkers

KAIN2/Game/STREAM.C
https://decomp.me/scratch/dVKsS
=> [STREAM]: Update RelocatePlanPool

KAIN2/Game/STREAM.C
https://decomp.me/scratch/HH6Y1
=> [STREAM]: Update RelocateVMObjects

KAIN2/Game/STREAM.C
https://decomp.me/scratch/iSDRN
=> [STREAM]: Update RelocateTerrain

KAIN2/Game/STREAM.C
https://decomp.me/scratch/IU4QB
=> [STREAM]: Update RelocateLevelWithInstances

KAIN2/Game/STREAM.C
=> Revert "[STREAM]: Update RelocateSFXMarkers"

KAIN2/Game/STREAM.C
=> Revert "[STREAM]: Update RelocatePlanMarkers"

KAIN2/Game/STREAM.C
https://decomp.me/scratch/ignyZ
=> [STREAM]: Update RelocateCameras

KAIN2/Game/STREAM.C
https://decomp.me/scratch/meV7V
=> [STREAM]: Update RelocateLevel

KAIN2/Game/STREAM.C
https://decomp.me/scratch/rjj3D
=> [STREAM]: Update STREAM_PackVRAMObject

KAIN2/Game/STREAM.C
https://decomp.me/scratch/6S8WU
=> [STREAM]: Update RelocateStreamPortals

KAIN2/Game/STREAM.C
https://decomp.me/scratch/6Pb7V
=> [STREAM]: Update RelocateInstances

KAIN2/Game/STREAM.C
https://decomp.me/scratch/c7C9V
=> [STREAM]: Update STREAM_SetInstancePosition

KAIN2/Game/STREAM.C
https://decomp.me/scratch/1EDQI
=> [STREAM]: Update STREAM_OffsetInstancePosition

KAIN2/Game/STREAM.C
https://decomp.me/scratch/oG7Q8
=> [STREAM]: Update STREAM_RelocateInstance

KAIN2/Game/STREAM.C
https://decomp.me/scratch/ahhXj
=> [STREAM]: Update STREAM_AdjustMultiSpline

KAIN2/Game/STREAM.C
https://decomp.me/scratch/ZJ1ip
=> [STREAM]: Update STREAM_MORPH_Relocate

KAIN2/Game/STREAM.C
https://decomp.me/scratch/bscA7
=> [STREAM]: Update MORPH_Continue

KAIN2/Game/STREAM.C
https://decomp.me/scratch/J7JtP
=> [STREAM]: Update MORPH_UpdateTextures

KAIN2/Game/STREAM.C
https://decomp.me/scratch/R5MX0
=> [STREAM]: Update MORPH_DoStep

KAIN2/Game/MATH3D.H, KAIN2/Game/STREAM.C
https://decomp.me/scratch/c1bE6
=> [STREAM]: Update RelocateSavedCameras

KAIN2/Game/STREAM.C
https://decomp.me/scratch/1DJgU
=> [STREAM]: Update MORPH_UpdateTrackingPoint

KAIN2/Game/EVENT.C
https://decomp.me/scratch/0zc9C
=> [EVENT]: Update EVENT_LoadEventsForLevel

KAIN2/Game/STREAM.C
https://decomp.me/scratch/YXM51
=> [STREAM]: Update RelocateBGObjects

KAIN2/Game/MONSTER/MONAPI.C
https://decomp.me/scratch/wq8Nn
=> [MONAPI]: Update TranslateAnimList

KAIN2/Game/MONSTER/MONLIB.C
https://decomp.me/scratch/UBzcn
=> [MONLIB]: Update MON_TurnOnAllSpheres

KAIN2/Game/MONSTER/MONLIB.C
https://decomp.me/scratch/h7TBX
=> [MONLIB]: Update MON_TransNodeAnimation

KAIN2/Game/MONSTER/MONLIB.C
https://decomp.me/scratch/sEQ1h
=> [MONLIB]: Update MON_PlayAnimFromList

KAIN2/Game/MONSTER/MONLIB.C
https://decomp.me/scratch/o0iGl
=> [MONLIB]: Update MON_PlayAnimIDIfNotPlaying

KAIN2/Game/MONSTER/MONLIB.C
https://decomp.me/scratch/QnrYW
=> [MONLIB]: Update MON_AnimPlayingFromList

KAIN2/Game/MONSTER/MONLIB.C
https://decomp.me/scratch/rgWpO
=> [MONLIB]: Update MON_PlayAnimFromListIfNotPlaying

KAIN2/Game/MONSTER/MONLIB.C
https://decomp.me/scratch/S5l73
=> [MONLIB]: Update MON_PlayAnim

KAIN2/Game/MONSTER/MONLIB.C
https://decomp.me/scratch/RAZnl
=> [MONLIB]: Update MON_AnimPlaying

KAIN2/Game/MONSTER/MONLIB.C
https://decomp.me/scratch/1q9Lf
=> [MONLIB]: Update MON_PlayAnimIfNotPlaying

KAIN2/Game/MONSTER/MONLIB.C
https://decomp.me/scratch/FZxs6
=> [MONLIB]: Update MON_FacingOffset

KAIN2/Game/MONSTER/MONLIB.C
https://decomp.me/scratch/g9VlS
=> [MONLIB]: Update MON_PlayCombatIdle

KAIN2/Game/MONSTER/MONLIB.C
https://decomp.me/scratch/xKEMM
=> [MONLIB]: Update MON_MoveForward

KAIN2/Game/MONSTER/MONLIB.C
https://decomp.me/scratch/hHa6b
=> [MONLIB]: Update MON_MoveToPosition

KAIN2/Game/MONSTER/MONLIB.C
https://decomp.me/scratch/NvYNO
=> [MONLIB]: Update MON_ApplyPhysics

KAIN2/Game/STREAM.C
https://decomp.me/scratch/4Ojv3
=> [STREAM]: Update MORPH_UpdateTimeMult

KAIN2/Game/MONSTER/MONLIB.C
https://decomp.me/scratch/GDChq
=> [MONLIB]: Update MON_GetTime

KAIN2/Game/MONSTER/MONLIB.C
https://decomp.me/scratch/u8kKg
=> [MONLIB]: Update MON_GetPlanSlot

KAIN2/Game/MONSTER/MONLIB.C
https://decomp.me/scratch/YXl8O
=> [MONLIB]: Update MON_ValidPosition

KAIN2/Game/MONSTER/MONSTER.H
=> [MONSTER]: Update structs

KAIN2/Game/MONSTER/MONSTER.C
https://decomp.me/scratch/V2mCt
=> [MONSTER]: Update MON_Birth

KAIN2/Game/MONSTER/MONSTER.C
https://decomp.me/scratch/3dmkK
=> [MONSTER]: Update MON_Parry

KAIN2/Game/MONSTER/MONSTER.C
https://decomp.me/scratch/4ubV9
=> [MONSTER]: Update MON_LandInWaterEntry

KAIN2/Game/MONSTER/MONSTER.C
https://decomp.me/scratch/A405E
=> [MONSTER]: Update MON_LandInWater

KAIN2/Game/MONSTER/MONSTER.C
https://decomp.me/scratch/rUDfA
=> [MONSTER]: Update MON_CombatEntry

KAIN2/Game/MONSTER/MONSTER.C
https://decomp.me/scratch/1BTra
=> [MONSTER]: Update MON_FleeEntry

KAIN2/Game/MONSTER/MONSTER.C
https://decomp.me/scratch/YukgN
=> [MONSTER]: Update MONSTER_CalcDamageIntensity

KAIN2/Game/MONSTER/MONSTER.C
https://decomp.me/scratch/r9bsS
=> [MONSTER]: Update MON_DefaultInit

KAIN2/Game/MONSTER/MONSTER.C
https://decomp.me/scratch/uWpiq
=> [MONSTER]: Update MON_SurpriseAttack

KAIN2/Game/MONSTER/MONSTER.C
https://decomp.me/scratch/5CBSa
=> [MONSTER]: Update MON_HideEntry

KAIN2/Game/MONSTER/MONSTER.C
https://decomp.me/scratch/C5MGF
=> [MONSTER]: Update MON_PetrifiedEntry

KAIN2/Game/MONSTER/MONLIB.C
https://decomp.me/scratch/F5ou3
=> [MONLIB]: Implement MON_AnimIDPlaying

KAIN2/Game/MONSTER/MONLIB.C
https://decomp.me/scratch/VMBo0
=> [MONLIB]: Update MON_GetAnim

KAIN2/Game/MONSTER/MONLIB.C
https://decomp.me/scratch/vXI5p
=> [MONLIB]: Update MON_TurnOffAllSpheres

KAIN2/Game/STREAM.C
https://decomp.me/scratch/JyBId
=> [STREAM]: Update MORPH_ToggleMorph

KAIN2/Game/STREAM.C
https://decomp.me/scratch/Hakjl
=> [STREAM]: Update MORPH_SetupInstanceListFlags

KAIN2/Game/STREAM.C
https://decomp.me/scratch/BvHHn
=> [STREAM]: Update MORPH_InMorphInstanceListFlags

KAIN2/Game/STREAM.C
https://decomp.me/scratch/fsZyG
=> [STREAM]: Update MORPH_InMorphDoFadeValues

KAIN2/Game/STREAM.C
https://decomp.me/scratch/uhV1q
=> [STREAM]: Update MORPH_UpdateNormals

KAIN2/Game/STREAM.C
https://decomp.me/scratch/F9qPR
=> [STREAM]: Update MORPH_AddOffsets

KAIN2/Game/STREAM.C
https://decomp.me/scratch/TNQoI
=> [STREAM]: Update MORPH_SubtractOffsets

KAIN2/Game/STREAM.C
https://decomp.me/scratch/SnmHe
=> [STREAM]: Update MORPH_AveragePoint

KAIN2/Game/MONSTER/MONSTER.C
https://decomp.me/scratch/GLbu6
=> [MONSTER]: Update MON_ProjectileEntry

KAIN2/Game/MONSTER/MONSTER.C
https://decomp.me/scratch/9CMxW
=> [MONSTER]: Update MON_ParryEntry

KAIN2/Game/STREAM.H
=> [STREAM]: Update structs

KAIN2/Game/STREAM.C
https://decomp.me/scratch/8mNWG
=> [STREAM]: Update STREAM_DumpNonResidentObjects

KAIN2/Game/STREAM.C
https://decomp.me/scratch/evG18
=> [STREAM]: Update WARPGATE_DrawWarpGateRim

KAIN2/Game/STREAM.C
Matching - 99.88%
https://decomp.me/scratch/C4dmW
=> [STREAM]: Update STREAM_RenderAdjacantUnit

KAIN2/Game/STREAM.C
https://decomp.me/scratch/TKIUt
=> [STREAM]: Update CalcVert

KAIN2/Game/STRMLOAD.C
https://decomp.me/scratch/kwMJz
=> [STRMLOAD]: Update LOAD_AbortDirectoryChange

KAIN2/Game/STRMLOAD.C
https://decomp.me/scratch/0EWn6
=> [STRMLOAD]: Update LOAD_ChangeDirectory

KAIN2/Game/STRMLOAD.C
https://decomp.me/scratch/JyumB
=> [STRMLOAD]: Update LOAD_ReadFile

KAIN2/Game/STRMLOAD.C
https://decomp.me/scratch/YL576
=> [STRMLOAD]: Update LOAD_PlayXA

KAIN2/Game/STRMLOAD.C
https://decomp.me/scratch/RhZ0c
=> [STRMLOAD]: Update LOAD_IsXAInQueue

KAIN2/Game/STRMLOAD.C
https://decomp.me/scratch/Lw1rw
=> [STRMLOAD]: Update LOAD_NonBlockingBufferedLoad

KAIN2/Game/STRMLOAD.C
https://decomp.me/scratch/4nOG4
=> [STRMLOAD]: Update STREAM_QueueNonblockingLoads

KAIN2/Game/STRMLOAD.C
https://decomp.me/scratch/tAQi9
=> [STRMLOAD]: Update LOAD_LoadToAddress

KAIN2/Game/STRMLOAD.C
Matching - 98.77%
https://decomp.me/scratch/05Dkb
=> [STRMLOAD]: Update STREAM_PollLoadQueue

KAIN2/Game/STRMLOAD.C
https://decomp.me/scratch/buKAE
=> [STRMLOAD]: Update STREAM_IsCdBusy

KAIN2/Game/STRMLOAD.C
https://decomp.me/scratch/IJkJE
=> [STRMLOAD]: Update STREAM_RemoveQueueEntry

KAIN2/Game/STRMLOAD.C
https://decomp.me/scratch/oRihd
=> [STRMLOAD]: Update STREAM_RemoveQueueHead

KAIN2/Game/STRMLOAD.C
https://decomp.me/scratch/nLUNC
=> [STRMLOAD]: Update STREAM_NextLoadAsNormal

KAIN2/Game/STRMLOAD.C
https://decomp.me/scratch/VOJ4r
=> [STRMLOAD]: Update STREAM_AddQueueEntryToTail

KAIN2/Game/STRMLOAD.C
https://decomp.me/scratch/gcB3M
=> [STRMLOAD]: Update STREAM_AddQueueEntryToHead

KAIN2/Game/STRMLOAD.H
=> [STRMLOAD]: Update structs

KAIN2/Game/VM.C
https://decomp.me/scratch/HThaY
=> [VM]: Update VM_Tick

KAIN2/Game/MONSTER/MONTABLE.C
https://decomp.me/scratch/grkmw
=> [MONTABLE]: Update MONTABLE_SetMessageFunc

KAIN2/Game/MONSTER/MONTABLE.C
https://decomp.me/scratch/yibyE
=> [MONTABLE]: Update MONTABLE_SetQueryFunc

KAIN2/Game/MONSTER/MONTABLE.C
https://decomp.me/scratch/N5NRU
=> [MONTABLE]: Update MONTABLE_GetCleanUpFunc

KAIN2/Game/MONSTER/MONTABLE.C
https://decomp.me/scratch/DkZYe
=> [MONTABLE]: Update MONTABLE_GetInitFunc

KAIN2/Game/MONSTER/MONTABLE.C
https://decomp.me/scratch/VwYe2
=> [MONTABLE]: Update MONTABLE_GetDamageEffectFunc

KAIN2/Game/VRAM.C
https://decomp.me/scratch/MmLKD
=> [VRAM]: Update VRAM_ConcatanateMemory

KAIN2/Game/VRAM.C
https://decomp.me/scratch/4KKXa
=> [VRAM]: Update VRAM_PrintInfo

KAIN2/Game/VRAM.C
https://decomp.me/scratch/bHHru
=> [VRAM]: Update VRAM_InitVramBlockCache

KAIN2/Game/VRAM.C
https://decomp.me/scratch/W4Q3g
=> [VRAM]: Update VRAM_EnableTerrainArea

KAIN2/Game/STRMLOAD.C
https://decomp.me/scratch/Zifcl
=> [STRMLOAD]: Update STREAM_NextLoadFromHead

KAIN2/Game/VRAM.C
https://decomp.me/scratch/MkWrH
=> [VRAM]: Update VRAM_DisableTerrainArea

KAIN2/Game/VRAM.C
https://decomp.me/scratch/JSvgW
=> [VRAM]: Update VRAM_DeleteFreeBlock

KAIN2/Game/VM.C
Matching - 99.84%
https://decomp.me/scratch/8YXxb
=> [VM]: Update VM_UpdateMorph

KAIN2/Game/VRAM.C
https://decomp.me/scratch/KoOOa
=> [VRAM]: Update VRAM_GarbageCollect

KAIN2/Game/VRAM.C
https://decomp.me/scratch/5fwBH
=> [VRAM]: Update VRAM_InsertFreeBlock

KAIN2/Game/VRAM.C
https://decomp.me/scratch/ntAno
=> [VRAM]: Update VRAM_InsertUsedBlock

KAIN2/Game/VRAM.C
https://decomp.me/scratch/XN5n8
=> [VRAM]: Update VRAM_LoadReturn

KAIN2/Game/VRAM.C
https://decomp.me/scratch/1FYHW
=> [VRAM]: Update VRAM_GetOpenBlock

KAIN2/Game/VRAM.C
https://decomp.me/scratch/xlVsq
=> [VRAM]: Update VRAM_DeleteUsedBlock

KAIN2/Game/BSP.C
https://decomp.me/scratch/o6xbV
=> [BSP]: Update SBSP_IntroduceInstancesAndLights

KAIN2/Game/BSP.H
=> [BSP]: Update symbols

KAIN2/Game/RAZIEL/STEERING.C
https://decomp.me/scratch/A5Ggy
=> [STEERING]: Update GetControllerInput

KAIN2/Game/RAZIEL/STEERING.C
https://decomp.me/scratch/ybPX8
=> [STEERING]: Update UpdateZoneDelta

KAIN2/Game/RAZIEL/STEERING.C
https://decomp.me/scratch/OioxE
=> [STEERING]: Update DecodeDirection

KAIN2/Game/VRAM.C
https://decomp.me/scratch/Ap6sV
=> [VRAM]: Update VRAM_ClearVramBlock

KAIN2/Game/VRAM.H
=> [VRAM]: Update structs

KAIN2/Game/VRAM.C, KAIN2/Game/VRAM.H
=> [VRAM]: Update symbols

KAIN2/Game/VM.C, KAIN2/Game/VM.H
=> [VM]: Update symbols

KAIN2/Game/VOICEXA.H
=> [VOICEXA]: Update structs

KAIN2/Game/UNDRWRLD.C, KAIN2/Game/UNDRWRLD.H
=> [UNDRWLRD]: Update symbols

KAIN2/Game/VOICEXA.C, KAIN2/Game/VOICEXA.H
=> [VOICEXA]: Update symbols

KAIN2/Game/UNDRWRLD.C
https://decomp.me/scratch/hEBNL
=> [UNDRWRLD]: Update UNDERWORLD_StartProcess

KAIN2/Game/GLYPH.C
Matching - 98.45%
https://decomp.me/scratch/51Wkc
=> [GLYPH]: Update GlyphInit

KAIN2/Game/GLYPH.C
https://decomp.me/scratch/Hhcwz
=> [GLYPH]: Update GlyphProcess

KAIN2/Game/GLYPH.C
https://decomp.me/scratch/ev763
=> [GLYPH]: Update GlyphQuery

KAIN2/Game/GLYPH.C
https://decomp.me/scratch/B9UDs
=> [GLYPH]: Update GlyphPost

KAIN2/Game/GLYPH.C
https://decomp.me/scratch/F7TLT
=> [GLYPH]: Update GlyphIsGlyphOpen

KAIN2/Game/STRMLOAD.C
=> [STRMLOAD]: Update symbols

KAIN2/Game/STREAM.C, KAIN2/Game/STREAM.H
=> [STREAM]: Update symbols

KAIN2/Game/STATE.H
=> [STATE]: Update structs

KAIN2/Game/STATE.C
=> [STATE]: Update symbols

KAIN2/Game/STATE.C
https://decomp.me/scratch/KpSRv
=> [STATE]: Update InitMessageQueue

KAIN2/Game/STATE.C
https://decomp.me/scratch/bp2eT
=> [STATE]: Update PurgeMessageQueue

KAIN2/Game/STATE.C
https://decomp.me/scratch/KBA8H
=> [STATE]: Update EnMessageQueue

KAIN2/Game/STATE.C
https://decomp.me/scratch/ZrODT
=> [STATE]: Update SetMonsterHitData

KAIN2/Game/STATE.C
https://decomp.me/scratch/rl5V8
=> [STATE]: Update SetMonsterSoulSuckData

KAIN2/Game/STATE.C
https://decomp.me/scratch/mOuu5
=> [STATE]: Update SetPositionData

KAIN2/Game/STATE.C
https://decomp.me/scratch/5mHPT
=> [STATE]: Update SetPhysicsGravityData

KAIN2/Game/STATE.C
https://decomp.me/scratch/l4KQ5
=> [STATE]: Update SetPhysicsEdgeData

KAIN2/Game/STRMLOAD.C
https://decomp.me/scratch/q0Kal
=> [STRMLOAD]: Update STREAM_SetUpQueueEntry

KAIN2/Game/STATE.C
https://decomp.me/scratch/NxWA9
=> [STATE]: Update SetPhysicsSwimData

KAIN2/Game/STATE.C
https://decomp.me/scratch/K59un
=> [STATE]: Update SetPhysicsDropOffData

KAIN2/Game/STATE.C
https://decomp.me/scratch/xB0Kb
=> [STATE]: Update SetPhysicsSlideData

KAIN2/Game/STATE.C
https://decomp.me/scratch/VFIxP
=> [STATE]: Update SetPhysicsWallCrawlData

KAIN2/Game/STREAM.C
https://decomp.me/scratch/pwbxf
=> [STREAM]: Update WARPGATE_IsItActive

KAIN2/Game/STATE.C
https://decomp.me/scratch/DdtAI
=> [STATE]: Update SetMonsterAlarmData

KAIN2/Game/STATE.C
https://decomp.me/scratch/tXz5Y
=> [STATE]: Update SetMonsterImpaleData

KAIN2/Game/STATE.C
https://decomp.me/scratch/Fo7zX
=> [STATE]: Update SetPhysicsDropHeightData

KAIN2/Game/STATE.C
https://decomp.me/scratch/K86L3
=> [STATE]: Update SetAnimationInstanceSwitchData

KAIN2/Game/STATE.C
https://decomp.me/scratch/W6Uzu
=> [STATE]: Update SetAnimationControllerDoneData

KAIN2/Game/INSTANCE.C
https://decomp.me/scratch/L4VNS
=> [INSTANCE]: Implement INSTANCE_InPlane

KAIN2/Game/INSTANCE.C
https://decomp.me/scratch/70fEX
=> [INSTANCE]: Update INSTANCE_FindWithName

KAIN2/Game/STATE.C
https://decomp.me/scratch/Q9gVx
=> [STATE]: Update SetObjectThrowData

KAIN2/Game/STATE.C
Matching - 99.71%
https://decomp.me/scratch/u2VSw
=> [STATE]: Update CIRC_Alloc

KAIN2/Game/STATE.C
https://decomp.me/scratch/8fpZn
=> [STATE]: Update SetControlInitHangData

KAIN2/Game/STATE.C
https://decomp.me/scratch/2J9qk
=> [STATE]: Update SetControlInitIdleData

KAIN2/Game/STATE.C
https://decomp.me/scratch/PXfaM
=> [STATE]: Update SetObjectAbsorbData

KAIN2/Game/STATE.C
https://decomp.me/scratch/gbuBs
=> [STATE]: Update SetControlSaveDataData

KAIN2/Game/STATE.C
https://decomp.me/scratch/XB8Y1
=> [STATE]: Update SetObjectIdleData

KAIN2/Game/STATE.C
https://decomp.me/scratch/ZMKA3
=> [STATE]: Update SetObjectBirthProjectileData

KAIN2/Game/STATE.C
https://decomp.me/scratch/uOjl8
=> [STATE]: Update SetShadowSegmentData

KAIN2/Game/SPLINE.H
=> [SPLINE]: Update structs

KAIN2/Game/UNDRWRLD.C
https://decomp.me/scratch/Sdm9e
=> [UNDRWRLD]: Update UNDERWORLD_InitDisplayProcess

KAIN2/Game/RAZIEL/STEERING.C
https://decomp.me/scratch/82kwI
=> [STEERING]: Update razDeinitWallCrawlSteering

KAIN2/Game/RAZIEL/STEERING.C
https://decomp.me/scratch/W4MzA
=> [STEERING]: Update razInitWallCrawlSteering

KAIN2/Game/STREAM.C
https://decomp.me/scratch/CC8fg
=> [STREAM]: Update WARPGATE_IncrementIndex

KAIN2/Game/STREAM.C
https://decomp.me/scratch/rxNuP
=> [STREAM]: Update STREAM_TryAndDumpNonResident

KAIN2/Game/RAZIEL/STEERING.C
https://decomp.me/scratch/8V4SJ
=> [STEERING]: Update SteerDisableAutoFace

KAIN2/Game/RAZIEL/STEERING.C
https://decomp.me/scratch/NVTDH
=> [STEERING]: Update SteerTurn

KAIN2/Game/STREAM.C
https://decomp.me/scratch/kkI6W
=> [STREAM]: Update PreloadAllConnectedUnits

KAIN2/Game/STREAM.C
https://decomp.me/scratch/Nsank
=> [STREAM]: Update STREAM_DumpUnit

KAIN2/Game/STREAM.C
https://decomp.me/scratch/ANLii
=> [STREAM]: Update STREAM_ConnectStream

KAIN2/Game/EVENT.C
https://decomp.me/scratch/KrzEU
=> [EVENT]: Update EVENT_AddGameObjectToStack

KAIN2/Game/SOUND.H
=> [SOUND]: Update structs

KAIN2/Game/RAZIEL/STEERING.C
https://decomp.me/scratch/n6qYd
=> [STEERING]: Update SteerSwitchMode

KAIN2/Game/RAZIEL/STEERING.C
https://decomp.me/scratch/pmpbA
=> [STEERING]: Update SteerWallcrawling

KAIN2/Game/RAZIEL/STEERING.C
Matching - 99.67%
https://decomp.me/scratch/1VzQt
=> [STEERING]: Update SteerSwim

KAIN2/Game/RAZIEL/STEERING.C
https://decomp.me/scratch/QjsLM
=> [STEERING]: Update SteerAutoFace

KAIN2/Game/RAZIEL/STEERING.C
https://decomp.me/scratch/kObAD
=> [STEERING]: Update SteerMove

KAIN2/Game/RAZIEL/STEERING.C
=> [STEERING]: Update symbols

KAIN2/Game/STATE.C
https://decomp.me/scratch/Ddv5j
=> [STATE]: Update G2EmulationInit

KAIN2/Game/STATE.C
https://decomp.me/scratch/8pxEi
=> [STATE]: Update G2EmulationInstancePlayAnimation

KAIN2/Game/STATE.C
https://decomp.me/scratch/aIiz2
=> [STATE]: Update G2EmulatePlayAnimation

KAIN2/Game/STATE.C
https://decomp.me/scratch/ZRhM7
=> [STATE]: Update G2EmulationInstanceSwitchAnimation

KAIN2/Game/STATE.C
https://decomp.me/scratch/kPmDD
=> [STATE]: Update G2EmulationInstanceSwitchAnimationAlpha

KAIN2/Game/STATE.C
https://decomp.me/scratch/Qf7nU
=> [STATE]: Update G2EmulationSwitchAnimation

KAIN2/Game/STATE.C
https://decomp.me/scratch/k7ABp
=> [STATE]: Update G2EmulationSwitchAnimationAlpha

KAIN2/Game/STATE.C
https://decomp.me/scratch/2tYVq
=> [STATE]: Update G2EmulationSwitchAnimationCharacter

KAIN2/Game/UNDRWRLD.C
https://decomp.me/scratch/tZbSu
=> [UNDRWRLD]: Update UNDERWORLD_SetupSource

KAIN2/Game/STATE.C
https://decomp.me/scratch/l4JiR
=> [STATE]: Update G2EmulationInstanceSetAnimation

KAIN2/Game/STATE.C
https://decomp.me/scratch/rZbXB
=> [STATE]: Update G2EmulationSetAnimation

KAIN2/Game/STATE.C
https://decomp.me/scratch/Xr5Uh
=> [STATE]: Update G2EmulationInstanceSetMode

KAIN2/Game/STATE.C
https://decomp.me/scratch/bb77R
=> [STATE]: Update G2EmulationSetMode

KAIN2/Game/STATE.C
https://decomp.me/scratch/dcrvp
=> [STATE]: Update G2EmulationInstanceQueryAnimation

KAIN2/Game/STATE.C
https://decomp.me/scratch/ipTaP
=> [STATE]: Update G2EmulationQueryAnimation

KAIN2/Game/STATE.C
https://decomp.me/scratch/gOFJ6
=> [STATE]: Update G2EmulationInstanceQueryFrame

KAIN2/Game/STATE.C
https://decomp.me/scratch/akg1x
=> [STATE]: Update G2EmulationInstanceQueryLastFrame

KAIN2/Game/STATE.C
https://decomp.me/scratch/lD7sX
=> [STATE]: Update G2EmulationSetInterpController_Vector

KAIN2/Game/STATE.C
https://decomp.me/scratch/iR4QV
=> [STATE]: Update G2EmulationQueryFrame

KAIN2/Game/STATE.C
https://decomp.me/scratch/zQlM7
=> [STATE]: Update G2EmulationQueryMode

KAIN2/Game/STATE.C
https://decomp.me/scratch/gJine
=> [STATE]: Update G2EmulationInstanceSetStartAndEndSegment

KAIN2/Game/STATE.C
https://decomp.me/scratch/PYucI
=> [STATE]: Update G2EmulationSetStartAndEndSegment

KAIN2/Game/STATE.C
https://decomp.me/scratch/NKY0f
=> [STATE]: Update G2EmulationInstanceSetTotalSections

KAIN2/Game/STATE.C
https://decomp.me/scratch/WOsrA
=> [STATE]: Update G2EmulationSetTotalSections

KAIN2/Game/STATE.C
https://decomp.me/scratch/OSjyx
=> [STATE]: Update StateSwitchStateDataDefault
