Gh0stBlade/KAIN2

- KAIN2/Game/STATE.C
https://decomp.me/scratch/jqwE7
> [STATE]: Update StateSwitchStateCharacterDataDefault

- KAIN2/Game/STATE.C
https://decomp.me/scratch/82Ah1
> [STATE]: Update StateSwitchStateCharacterData

- KAIN2/Game/STATE.C
https://decomp.me/scratch/itpSg
> [STATE]: Update StateGovernState

- KAIN2/Game/SPLINE.C
https://decomp.me/scratch/SSnC1
> [SPLINE]: Update SplineGetFirstRot

- KAIN2/Game/SPLINE.C
https://decomp.me/scratch/EOnie
> [SPLINE]: Update SplineGetFirstPoint

- KAIN2/Game/SPLINE.C
https://decomp.me/scratch/QWAni
> [SPLINE]: Update SplineGetNextPoint

- KAIN2/Game/SPLINE.C
https://decomp.me/scratch/tkRDt
> [SPLINE]: Update SplineGetPreviousPoint

- KAIN2/Game/SPLINE.C
https://decomp.me/scratch/sMgnj
> [SPLINE]: Update SplineGetOffsetNextPoint

- KAIN2/Game/SPLINE.C
https://decomp.me/scratch/oZj4d
> [SPLINE]: Update SplineGetOffsetPreviousPoint

- KAIN2/Game/SIGNAL.C
https://decomp.me/scratch/lulL6
> [SIGNAL]: Update SIGNAL_HandleCameraAdjust

- KAIN2/Game/SIGNAL.C
https://decomp.me/scratch/heyBM
> [SIGNAL]: Update SIGNAL_HandleCamera

- KAIN2/Game/SIGNAL.C
https://decomp.me/scratch/wOZAT
> [SIGNAL]: Update SIGNAL_HandleCameraMode

- KAIN2/Game/SIGNAL.C
https://decomp.me/scratch/8Bd4w
> [SIGNAL]: Update SIGNAL_HandleCameraLock

- KAIN2/Game/SIGNAL.C
https://decomp.me/scratch/14dHE
> [SIGNAL]: Update SIGNAL_HandleCameraUnlock

- KAIN2/Game/SIGNAL.C
https://decomp.me/scratch/D5Haa
> [SIGNAL]: Update SIGNAL_HandleCameraSmooth

- KAIN2/Game/SIGNAL.C
https://decomp.me/scratch/Spm6s
> [SIGNAL]: Update SIGNAL_HandleCameraSave

- KAIN2/Game/SIGNAL.C
https://decomp.me/scratch/XGFA6
> [SIGNAL]: Update SIGNAL_HandleCameraRestore

- KAIN2/Game/SIGNAL.C
https://decomp.me/scratch/8mF6z
> [SIGNAL]: Update SIGNAL_HandleCameraValue

- KAIN2/Game/SIGNAL.C
Matching - 98.68%
https://decomp.me/scratch/79YL5
> [SIGNAL]: Update SIGNAL_HandleStreamLevel

- KAIN2/Game/SIGNAL.C
https://decomp.me/scratch/abKA7
> [SIGNAL]: Update SIGNAL_HandleFogNear

- KAIN2/Game/SIGNAL.C
https://decomp.me/scratch/g6Vjl
> [SIGNAL]: Update SIGNAL_HandleFogFar

- KAIN2/Game/SIGNAL.C
https://decomp.me/scratch/qkIva
> [SIGNAL]: Update SIGNAL_HandleStopPlayerControl

- KAIN2/Game/SIGNAL.C
https://decomp.me/scratch/ru5Ui
> [SIGNAL]: Update SIGNAL_HandleStartPlayerControl

- KAIN2/Game/COLLIDE.C
Matching - 99.94%
https://decomp.me/scratch/GTDVT
> [COLLIDE]: Update COLLIDE_PointInTriangle

- KAIN2/Game/STREAM.C
https://decomp.me/scratch/aYINg
> [STREAM]: Update MORPH_SetupInstanceFlags

- KAIN2/Game/COLLIDE.C
Matching - 99.06%
https://decomp.me/scratch/t4u5q
> [COLLIDE]: Update COLLIDE_PointAndTfaceFunc

- KAIN2/Game/SIGNAL.C
https://decomp.me/scratch/v7IRx
> [SIGNAL]: Update SIGNAL_HandleCameraShake

- KAIN2/Game/STRMLOAD.C
https://decomp.me/scratch/NN44B
> [STRMLOAD]: Update STREAM_InitLoader

- KAIN2/Game/STRMLOAD.C
https://decomp.me/scratch/Bf1u2
> [STRMLOAD]: Update LOAD_AbortFileLoad

- KAIN2/Game/MONSTER/MONTABLE.C
https://decomp.me/scratch/0hDBA
> [MONTABLE]: Update MONTABLE_SetupTablePointer

- KAIN2/Game/SIGNAL.C
https://decomp.me/scratch/qwPki
> [SIGNAL]: Update SIGNAL_HandleScreenWipe

- KAIN2/Game/SIGNAL.C
https://decomp.me/scratch/m19ul
> [SIGNAL]: Update SIGNAL_HandleBlendStart

- KAIN2/Game/SIGNAL.C
https://decomp.me/scratch/wTFrR
> [SIGNAL]: Update SIGNAL_HandleScreenWipeColor

- KAIN2/Game/MEMPACK.C
https://decomp.me/scratch/c8hTD
> [MEMPACK]: Update MEMPACK_RelocateObjectType

- KAIN2/Game/SIGNAL.C
https://decomp.me/scratch/Jrj5L
> [SIGNAL]: Implement SIGNAL_RelocateCamera

- KAIN2/Game/MONSTER/HUMAN.C
https://decomp.me/scratch/JTRei
> [HUMAN]: Update HUMAN_Init

- KAIN2/Game/EVENT.C
https://decomp.me/scratch/NCcFV
> [EVENT]: Implement EVENT_TransformSubListObjectAttribute

- KAIN2/Game/STATE.C
https://decomp.me/scratch/p1LZt
> [STATE]: Update G2EmulationInstanceQueryMode

- KAIN2/Game/EVENT.C
https://decomp.me/scratch/9P6Xx
> [EVENT]: Update EVENT_TransformObjectOnStack

- KAIN2/Game/EVENT.C
Further discussion is required about the validity of the non-SYMDUMP vars.
> [EVENT]: Unimplement EVENT_RemoveStreamToInstanceList

- KAIN2/Game/SIGNAL.C
https://decomp.me/scratch/ejfwY
> [SIGNAL]: Update SIGNAL_HandleLightGroup

- KAIN2/Game/SIGNAL.C
https://decomp.me/scratch/KSIgu
> [SIGNAL]: Update SIGNAL_InWater

- KAIN2/Game/SIGNAL.C
https://decomp.me/scratch/3T2tQ
> [SIGNAL]: Update SIGNAL_OutOfWater

- KAIN2/Game/SIGNAL.C
https://decomp.me/scratch/cVHLX
> [SIGNAL]: Update SIGNAL_HandleSignal

- KAIN2/Game/SIGNAL.C
https://decomp.me/scratch/cdOLu
> [SIGNAL]: Update SIGNAL_IsThisStreamAWarpGate

- KAIN2/Game/SIGNAL.C
https://decomp.me/scratch/qz10M
> [SIGNAL]: Update SIGNAL_HandleResetSlideAngle

- KAIN2/Game/SIGNAL.C
https://decomp.me/scratch/Gcjap
> [SIGNAL]: Implement SIGNAL_HandleEnd

- KAIN2/Game/EVENT.C
Matching - 99.31%
https://decomp.me/scratch/e0l6r
> [EVENT]: Update EVENT_TransformInstanceAttribute

- KAIN2/Game/EVENT.C
> Revert "[EVENT]: Unimplement EVENT_RemoveStreamToInstanceList"

- KAIN2/Game/UNDRWRLD.H
> [UNDRWRLD]: Remove unused structs

- KAIN2/Game/PIPE3D.H
> [PIPE3D]: Remove unused structs

- KAIN2/Game/OBTABLE.H
> [OBTABLE]: Remove unused structs

- KAIN2/Game/MATH3D.H
> [MATH3D]: Remove unused structs

- KAIN2/Game/INSTANCE.H
> [INSTANCE]: Remove unused structs

- KAIN2/Game/GLYPH.H
> [GLYPH]: Remove unused struct

- KAIN2/Game/GENERIC.H
> [GENERIC]: Remove unused structs

- KAIN2/Game/FX.H
> [FX]: Remove unused struct

- KAIN2/Game/FONT.H
> [FONT]: Remove unused structs

- KAIN2/Game/DEBUG.H
> [DEBUG]: Remove unused struct

- KAIN2/Game/BSP.H
> [BSP]: Remove unused structs

- KAIN2/Game/MONSTER/WORSHIP.H
> [WORSHIP]: Remove unused struct

- KAIN2/Game/MONSTER/VWRAITH.H
> [VWRAITH]: Remove unused struct

- KAIN2/Game/MONSTER/SOUL.H
> [SOUL]: Remove unused struct

- KAIN2/Game/MONSTER/SLUAGH.H
> [SLUAGH]: Remove unused struct

- KAIN2/Game/MONSTER/MORLOCK.H
> [MORLOCK]: Remove unused struct

- KAIN2/Game/MONSTER/MISSILE.H
> [MISSILE]: Remove unused struct

- KAIN2/Game/MONSTER/MBMISS.H
> [MBMISS]: Remove unused struct

- KAIN2/Game/MONSTER/HUMAN.H
> [HUMAN]: Remove unused struct

- KAIN2/Game/MENU/MENUUTIL.H
> [MENUUTIL]: Remove unused structs

- KAIN2/Game/MENU/MENUFACE.H
> [MENUFACE]: Remove unused structs

- KAIN2/Game/MENU/MENUDEFS.H
> [MENUDEFS]: Remove unused structs

- KAIN2/Game/MENU/MENU.H
> [MENU]: Remove unused structs

- KAIN2/Game/MCARD/MEMCARD.H
> [MEMCARD]: Remove unused structs

- KAIN2/Game/G2/ANIMG2.H
> [ANIMG2]: Remove unused struct

- KAIN2/Game/LIST.C
https://decomp.me/scratch/LcbvP
> [LIST]: Update LIST_InsertFunc

- KAIN2/Game/LIST.C
https://decomp.me/scratch/SXBXg
> [LIST]: Update LIST_GetFunc

- KAIN2/Game/EVENT.C
https://decomp.me/scratch/9hJOj
> [EVENT]: Update EVENT_WriteEventObject

- KAIN2/Game/EVENT.C
https://decomp.me/scratch/QhJux
> [EVENT]: Update EVENT_RemoveStreamToInstanceList

- KAIN2/Game/EVENT.C
https://decomp.me/scratch/VxAse
> [EVENT]: Update EVENT_DoAreaAction

- KAIN2/Game/SAVEINFO.H
> [SAVEINFO]: Update structs

- KAIN2/Game/LOAD3D.C
- KAIN2/Game/RESOLVE.C
- KAIN2/Game/RESOLVE.H
Updated struct to current game version symbols.
> [RESOLVE]: Update struct

- KAIN2/Game/REAVER.H
> [REAVER]: Update structs

- KAIN2/Game/PLAYER.H
> [PLAYER]: Update structs

- KAIN2/Game/PIPE3D.H
> [PIPE3D]: Update structs

- KAIN2/Game/PHYSOBS.H
> [PHYSOBS]: Update structs

- KAIN2/Game/OBTABLE.H
> [OBTABLE]: Update structs

- KAIN2/Game/MEMPACK.H
> [MEMPACK]: Update structs

- KAIN2/Game/MATH3D.H
Updated struct to current game version symbols.
> [MATH3D]: Update struct

- KAIN2/Game/EVENT.C
https://decomp.me/scratch/O5iOt
> [EVENT]: Update EVENT_TransformEventAttribute

- KAIN2/Game/EVENT.C
https://decomp.me/scratch/nRj5k
> [EVENT]: Update EVENT_TransformAreaAttribute

- KAIN2/Game/EVENT.C
https://decomp.me/scratch/iz4mx
> [EVENT]: Update EVENT_TransformSplineAttribute

- KAIN2/Game/EVENT.C
https://decomp.me/scratch/tJJKg
> [EVENT]: Update EVENT_TransformSoundObjectAttribute

- KAIN2/Game/EVENT.C
https://decomp.me/scratch/iqzsh
> [EVENT]: Update EVENT_TransformVector3dAttribute

- KAIN2/Game/EVENT.C
https://decomp.me/scratch/7aLtl
> [EVENT]: Update EVENT_TransformTGroupAttribute

- KAIN2/Game/SIGNAL.C
https://decomp.me/scratch/SqFH4
> [SIGNAL]: Update SIGNAL_IsStreamSignal

- KAIN2/Game/EVENT.C
Matching - 99.68%
https://decomp.me/scratch/L8frx
> [EVENT]: Update EVENT_TransformGameAttribute

- KAIN2/Game/STREAM.C
Matching - 55.56%
https://decomp.me/scratch/MXKsM
> [STREAM]: Update STREAM_IsSpecialMonster

- KAIN2/Game/STREAM.C
Matching - 55.56%
https://decomp.me/scratch/mnwyo
> [STREAM]: Update STREAM_IsMonster

- KAIN2/Game/GLYPH.C
https://decomp.me/scratch/zlo8p
> [GLYPH]: Update _GlyphSwitchProcess

- KAIN2/Game/GLYPH.C
https://decomp.me/scratch/CtZba
> [GLYPH]: Update _GlyphIsGlyphSet

- KAIN2/Game/GLYPH.C
https://decomp.me/scratch/Zulie
> [GLYPH]: Update _GlyphIsGlyphUsable

- KAIN2/Game/GLYPH.C
https://decomp.me/scratch/bT4bQ
> [GLYPH]: Update _GlyphDefaultProcess

- KAIN2/Game/GLYPH.C
https://decomp.me/scratch/xe5Ym
> [GLYPH]: Update Glyph_StartSpell

- KAIN2/Game/GLYPH.C
https://decomp.me/scratch/poZFC
> [GLYPH]: Update _GlyphIsAnyGlyphSet

- KAIN2/Game/GLYPH.C
https://decomp.me/scratch/qsGPI
> [GLYPH]: Update GlyphTime

- KAIN2/Game/LOAD3D.C
- KAIN2/Game/LOAD3D.H
- KAIN2/Game/STRMLOAD.C
> [LOAD3D]: Update structs

- KAIN2/Game/LIGHT3D.H
Updated struct to current game version symbols.
> [LIGHT3D]: Update struct

- KAIN2/Game/GLYPH.C
https://decomp.me/scratch/0fnph
> [GLYPH]: Update _GlyphOffProcess

- KAIN2/Game/GLYPH.C
https://decomp.me/scratch/fM0m2
> [GLYPH]: Update EnlargeGlyphMenu

- KAIN2/Game/GLYPH.C
https://decomp.me/scratch/zfeux
> [GLYPH]: Update ShrinkGlyphMenu

- KAIN2/Game/GLYPH.C
https://decomp.me/scratch/HSvpp
> [GLYPH]: Update Glyph_EndFX

- KAIN2/Game/GLYPH.C
https://decomp.me/scratch/2PRyd
> [GLYPH]: Update GlyphTrigger

- KAIN2/Game/GLYPH.C
https://decomp.me/scratch/cViUk
> [GLYPH]: Update MANNA_Pickup

- KAIN2/Game/GLYPH.C
https://decomp.me/scratch/gv8Pb
> [GLYPH]: Update HEALTHU_Pickup

- KAIN2/Game/GLYPH.C
Matching - 99.93%
https://decomp.me/scratch/hVjMC
> [GLYPH]: Update HUD_Draw

- KAIN2/Game/G2/ANMCTRLR.C
Matching - 99.29%
https://decomp.me/scratch/vcaJc
> [ANMCTRLR]: Update G2Anim_SetInterpController_Vector

- KAIN2/Game/FX.C
https://decomp.me/scratch/gXrrX
> [FX]: Update FX_GetPrim

- KAIN2/Game/FX.C
https://decomp.me/scratch/dooeh
> [FX]: Update FX_Die

- KAIN2/Game/FX.C
https://decomp.me/scratch/HAM3P
> [FX]: Update FX_DeleteGeneralEffect

- KAIN2/Game/FX.C
https://decomp.me/scratch/IFoIG
> [FX]: Update FX_GetParticle

- KAIN2/Game/GLYPH.C
https://decomp.me/scratch/LW7mp
> [GLYPH]: Update GlyphDrawMenu

- KAIN2/Game/OBTABLE.C
Fixed object name for Soul Reaver.
> [OBTABLE]: Fix typo

- KAIN2/Game/GLYPH.C
https://decomp.me/scratch/UQesk
> [GLYPH]: Update _GlyphGenericProcess

- KAIN2/Game/RAZIEL/RAZLIB.C
https://decomp.me/scratch/XgT3p
> [RAZLIB]: Update razEnterWater

- KAIN2/Game/DEBUG.C
https://decomp.me/scratch/8R5SD
> [DEBUG]: Update DEBUG_FogLoad

- KAIN2/Game/SAVEINFO.C
https://decomp.me/scratch/8Grcw
> [SAVEINFO]: Update SAVE_SaveableInstance

- KAIN2/Game/OBTABLE.C
https://decomp.me/scratch/h4Ia9
> [OBTABLE]: Update OBTABLE_GetInstanceCollideFunc

- KAIN2/Game/OBTABLE.C
https://decomp.me/scratch/exqjB
> [OBTABLE]: Update OBTABLE_GetInstanceProcessFunc

- KAIN2/Game/SIGNAL.C
https://decomp.me/scratch/Xf3Z3
> [SIGNAL]: Update SIGNAL_HandleSetSlideAngle

- KAIN2/Game/SIGNAL.C
https://decomp.me/scratch/S2xt6
> [SIGNAL]: Update SIGNAL_HandleSetCameraDistance

- KAIN2/Game/SIGNAL.C
https://decomp.me/scratch/VKp5N
> [SIGNAL]: Update SIGNAL_HandleCallSignal

- KAIN2/Game/OBTABLE.C
https://decomp.me/scratch/rb5jj
> [OBTABLE]: Update OBTABLE_GetInstanceQueryFunc

- KAIN2/Game/OBTABLE.C
https://decomp.me/scratch/PHiGO
> [OBTABLE]: Update OBTABLE_ClearObjectReferences

- KAIN2/Game/OBTABLE.C
https://decomp.me/scratch/fjmXB
> [OBTABLE]: Update OBTABLE_RemoveObjectEntry

- KAIN2/Game/OBTABLE.C
https://decomp.me/scratch/mrt8w
> [OBTABLE]: Update OBTABLE_ChangeObjectAccessPointers

- KAIN2/Game/OBTABLE.C
https://decomp.me/scratch/pkRsW
> [OBTABLE]: Update OBTABLE_InitAnimPointers

- KAIN2/Game/OBTABLE.C
https://decomp.me/scratch/7204h
> [OBTABLE]: Update OBTABLE_GetInstanceMessageFunc

- KAIN2/Game/SCRIPT.C
https://decomp.me/scratch/DJFCy
> [SCRIPT]: Update ScriptGetPosSpline

- KAIN2/Game/SCRIPT.C
https://decomp.me/scratch/k1YRg
> [SCRIPT]: Update ScriptGetRotSpline

- KAIN2/Game/SCRIPT.C
https://decomp.me/scratch/HgUx7
> [SCRIPT]: Update SCRIPT_GetMultiSpline

- KAIN2/Game/OBTABLE.C
https://decomp.me/scratch/PPvOH
> [OBTABLE]: Update OBTABLE_InstanceInit

- KAIN2/Game/OBTABLE.C
https://decomp.me/scratch/rY8yl
> [OBTABLE]: Update OBTABLE_GetInstanceAdditionalCollideFunc

- KAIN2/Game/OBTABLE.C
https://decomp.me/scratch/n80la
> [OBTABLE]: Update OBTABLE_RelocateInstanceObject

- KAIN2/Game/SCRIPT.C
https://decomp.me/scratch/HERq8
> [SCRIPT]: Update SCRIPT_GetPosSplineDef

- KAIN2/Game/SCRIPT.C
https://decomp.me/scratch/dzVKg
> [SCRIPT]: Update SCRIPT_GetRotSplineDef

- KAIN2/Game/SCRIPT.C
https://decomp.me/scratch/D7d7D
> [SCRIPT]: Update SCRIPT_GetSplineFrameNumber

- KAIN2/Game/SCRIPT.C
https://decomp.me/scratch/k8ZMQ
> [SCRIPT]: Update SCRIPT_InstanceSplineInit

- KAIN2/Game/PHYSOBS.C
https://decomp.me/scratch/zB6bp
> [PHYSOBS]: Update PHYSOB_CheckSlideNormal

- KAIN2/Game/PHYSOBS.C
https://decomp.me/scratch/VVQvQ
> [PHYSOBS]: Update CheckSlope

- KAIN2/Game/PHYSOBS.C
https://decomp.me/scratch/VTL7Z
> [PHYSOBS]: Update PHYSOBS_IsAnythingAttached

- KAIN2/Game/PHYSOBS.C
https://decomp.me/scratch/szRMI
> [PHYSOBS]: Update CheckPhysOb

- KAIN2/Game/PHYSOBS.C
https://decomp.me/scratch/f9H16
> [PHYSOBS]: Update CheckPhysObFamily

- KAIN2/Game/PHYSOBS.C
https://decomp.me/scratch/Tuwg1
> [PHYSOBS]: Update FinishPush

- KAIN2/Game/PHYSOBS.C
https://decomp.me/scratch/VY6CN
> [PHYSOBS]: Update PHYSOB_BirthProjectile

- KAIN2/Game/PHYSOBS.C
https://decomp.me/scratch/e8WMY
> [PHYSOBS]: Update PHYSOB_EndLighting

- KAIN2/Game/PHYSOBS.C
https://decomp.me/scratch/S1yyv
> [PHYSOBS]: Update PHYSOB_StartBurning

- KAIN2/Game/PHYSOBS.C
https://decomp.me/scratch/JXUEh
> [PHYSOBS]: Update PHYSOB_StopLighting

- KAIN2/Game/PHYSOBS.C
https://decomp.me/scratch/PpHLW
> [PHYSOBS]: Update PHYSOB_StopBurning

- KAIN2/Game/PHYSOBS.C
https://decomp.me/scratch/GJV8v
> [PHYSOBS]: Update StopPhysOb

- KAIN2/Game/PHYSOBS.C
https://decomp.me/scratch/3T3z2
> [PHYSOBS]: Update PhysObGetLight

- KAIN2/Game/PHYSOBS.C
https://decomp.me/scratch/27S9Z
> [PHYSOBS]: Update PhysObGetSplinter

- KAIN2/Game/PHYSOBS.C
https://decomp.me/scratch/xOtDu
> [PHYSOBS]: Update TurnOffCollisionPhysOb

- KAIN2/Game/PHYSOBS.C
https://decomp.me/scratch/m129m
> [PHYSOBS]: Update PHYSOB_EndBurning

- KAIN2/Game/MATH3D.H
- KAIN2/Game/STREAM.C
https://decomp.me/scratch/EkaKN
> [STREAM]: Update MORPH_GetComponentsForTrackingPoint

- KAIN2/Game/MEMPACK.C
https://decomp.me/scratch/IZIs7
> [MEMPACK]: Update MEMPACK_RelocateAreaType

- KAIN2/Game/REAVER.C
https://decomp.me/scratch/sRdHo
> [REAVER]: Update SoulReaverProcess

- KAIN2/Game/PHYSOBS.C
https://decomp.me/scratch/bmBKX
> [PHYSOBS]: Update PHYSOBS_SetNewAnim

- KAIN2/Game/PHYSOBS.C
https://decomp.me/scratch/tvm8x
> [PHYSOBS]: Update CheckPhysObAbility

- KAIN2/Game/STREAM.C
Matching - 86.63%
https://decomp.me/scratch/aztG8
> [STREAM]: Update STREAM_FinishLoad

- KAIN2/Game/SCRIPT.C
https://decomp.me/scratch/HCJZh
> [SCRIPT]: Update SCRIPT_GetScaleSplineDef

- KAIN2/Game/REAVER.C
https://decomp.me/scratch/ANxgz
> [REAVER]: Update StopSoulReaverCharge

- KAIN2/Game/REAVER.C
https://decomp.me/scratch/9yuRT
> [REAVER]: Update REAVER_GetGlowColor

- KAIN2/Game/REAVER.C
https://decomp.me/scratch/IV8kJ
> [REAVER]: Update SoulReaverFire

- KAIN2/Game/RAZCNTRL.C
https://decomp.me/scratch/clCRu
> [RAZCNTRL]: Update ProcessRazControl

- KAIN2/Game/SCRIPT.C
https://decomp.me/scratch/0cJ3A
> [SCRIPT]: Update SCRIPT_FadeOutProcess

- KAIN2/Game/PLAYER.C
https://decomp.me/scratch/MA5rn
> [PLAYER]: Update PLAYER_TurnHead

- KAIN2/Game/PLAYER.C
https://decomp.me/scratch/BpdSW
> [PLAYER]: Update PLAYER_OkToLookAround

- KAIN2/Game/PLAYER.C
https://decomp.me/scratch/cwV3C
> [PLAYER]: Update PLAYER_SetLookAround

- KAIN2/Game/PLAYER.C
https://decomp.me/scratch/UfqyN
> [PLAYER]: Update PLAYER_ReSetLookAround

- KAIN2/Game/PIPE3D.C
https://decomp.me/scratch/q8euH
> [PIPE3D]: Update PIPE3D_AspectAdjustMatrix

- KAIN2/Game/PIPE3D.C
Matching - 97.74%
https://decomp.me/scratch/FLW94
> [PIPE3D]: Update PIPE3D_CalculateWCTransform

- KAIN2/Game/PIPE3D.C
Matching - 96.44%
https://decomp.me/scratch/efGmJ
> [PIPE3D]: Update PIPE3D_NormalizeMatrix

- KAIN2/Game/PIPE3D.C
https://decomp.me/scratch/OxSOA
> [PIPE3D]: Update PIPE3D_MatrixColumnLength

- KAIN2/Game/PIPE3D.C
Matching - 90.68%
https://decomp.me/scratch/O6hCG
> [PIPE3D]: Update PIPE3D_InstanceTransformAndDraw

- KAIN2/Game/PIPE3D.C
Matching - 98.07%
https://decomp.me/scratch/YpfZf
> [PIPE3D]: Update PIPE3D_InstanceListTransformAndDrawFunc

- KAIN2/Game/PIPE3D.C
https://decomp.me/scratch/yQf7Q
> [PIPE3D]: Update PIPE3D_HalvePlaneGetRingPoints

- KAIN2/Game/PIPE3D.C
https://decomp.me/scratch/TzyZs
> [PIPE3D]: Update PIPE3D_HalvePlaneInstanceTransformAndDraw

- KAIN2/Game/PIPE3D.C
https://decomp.me/scratch/X5jiU
> [PIPE3D]: Update PIPE3D_InstanceListTransformAndDraw

- KAIN2/Game/DEBUG.C
https://decomp.me/scratch/py9Ez
> [DEBUG]: Update DEBUG_UpdateMana

- KAIN2/Game/PIPE3D.C
https://decomp.me/scratch/5hnOk
> [PIPE3D]: Update PIPE3D_InvertTransform

- KAIN2/Game/CAMERA.C
Matching - 98.95%
https://decomp.me/scratch/phwEy
> [CAMERA]: Update CAMERA_CalcFollowPosition

- KAIN2/Game/FX.C
https://decomp.me/scratch/UymoE
> [FX]: Update FX_CalcSpiral

- KAIN2/Game/FX.C
https://decomp.me/scratch/tH9qa
> [FX]: Update FX_Spiral_Init

- KAIN2/Game/FX.C
https://decomp.me/scratch/SByA8
> [FX]: Update FX_Health_Spiral

- KAIN2/Game/FX.C
https://decomp.me/scratch/ura8T
> [FX]: Update FX_SetReaverInstance

- KAIN2/Game/FX.C
https://decomp.me/scratch/AoIgp
> [FX]: Update FX_WaterRingProcess

- KAIN2/Game/RAZIEL/RAZIEL.C
https://decomp.me/scratch/a3404
> [RAZIEL]: Update StateHandlerLookAround

- KAIN2/Game/RAZIEL/HEALTH.C
https://decomp.me/scratch/67NKT
> [HEALTH]: Update razPlayUnderworldSounds

- KAIN2/Game/RAZIEL/HEALTH.C
https://decomp.me/scratch/G8kpL
> [HEALTH]: Update RAZIEL_DebugHealthFillUp

- KAIN2/Game/RAZIEL/HEALTH.C
https://decomp.me/scratch/hnuol
> [HEALTH]: Update LoseHealth

- KAIN2/Game/RAZIEL/SPIDER.C
https://decomp.me/scratch/A11Yh
> [SPIDER]: Update StateHandlerWallGrab

- KAIN2/Game/RAZIEL/RAZLIB.C
https://decomp.me/scratch/5P6eT
> [RAZLIB]: Update razAlignYRotMoveInterp

- KAIN2/Game/RAZIEL/PUPPET.C
https://decomp.me/scratch/1tsfo
> [PUPPET]: Update StateHandlerWarpGate

- KAIN2/Game/RAZIEL/ATTACK.C
https://decomp.me/scratch/nfreO
> [ATTACK]: Update StateHandlerCannedReaction

- KAIN2/Game/UNDRWRLD.C
Added comments about code that needs refactoring.
> [UNDRWRLD]: Stuff that needs fixing

- KAIN2/Game/TIMER.C
https://decomp.me/scratch/7NcDP
> [TIMER]: Update TIMER_GetTimeMS

- KAIN2/Game/PLAN/PLAN.C
https://decomp.me/scratch/FoJav
> [PLAN]: Update PLAN_AddInitialNodes

- KAIN2/Game/PLAN/PLAN.C
https://decomp.me/scratch/sgQWm
> [PLAN]: Update PLAN_AddOrRemoveNodes

- KAIN2/Game/PLAN/PLAN.C
https://decomp.me/scratch/duChm
> [PLAN]: Update PLAN_FindNodeMostInNeedOfConnectivityExpansion

- KAIN2/Game/PLAN/PLANSRCH.C
https://decomp.me/scratch/Zw2iz
> [PLANSRCH]: Update PLANSRCH_InitNodesForSearch

- KAIN2/Game/RAZIEL/RAZLIB.C
https://decomp.me/scratch/XW6vc
> [RAZLIB]: Update razPickupAndGrab

- KAIN2/Game/RAZIEL/RAZIEL.C
https://decomp.me/scratch/v8D7x
> [RAZIEL]: Update RazielAnimCallbackDuringPause

- KAIN2/Game/RAZIEL/HEALTH.C
https://decomp.me/scratch/pRIsZ
> [HEALTH]: Update HealthCheckForLowHealth

- KAIN2/Game/RAZIEL/PUPPET.C
https://decomp.me/scratch/MaW5Y
> [PUPPET]: Update DefaultPuppetStateHandler

- KAIN2/Game/RAZIEL/RAZIEL.C
https://decomp.me/scratch/nE2qI
> [RAZIEL]: Update RazielPost

- KAIN2/Game/DEBUG.C
https://decomp.me/scratch/wwQKG
> [DEBUG]: Update DEBUG_PageFlip

- KAIN2/Game/PLAN/PLANPOOL.C
https://decomp.me/scratch/1GdZh
> [PLANPOOL]: Update PLANPOOL_NumConnectionsExaminedForNode

- KAIN2/Game/MATH3D.C
https://decomp.me/scratch/3Gm5F
> [MATH3D]: Update MATH3D_FastAtan2

- KAIN2/Game/FX.C
https://decomp.me/scratch/1un1o
> [FX]: Update FX_Init

- KAIN2/Game/FX.C
https://decomp.me/scratch/O371E
> [FX]: Update FX_GetMatrix

- KAIN2/Game/FX.C
https://decomp.me/scratch/OXUpP
> [FX]: Update FX_StandardProcess

- KAIN2/Game/FX.C
https://decomp.me/scratch/vYk5C
> [FX]: Update _FX_SetupLighting

- KAIN2/Game/FX.C
https://decomp.me/scratch/XMwdy
> [FX]: Update FX_DFacadeProcess

- KAIN2/Game/MATH3D.C
Matching - 98.75%
https://decomp.me/scratch/mOLp3
> [MATH3D]: Update MATH3D_LengthXY

- KAIN2/Game/MATH3D.C
https://decomp.me/scratch/nhoAF
> [MATH3D]: Update MATH3D_FastSqrt

- KAIN2/Game/MATH3D.C
https://decomp.me/scratch/GFs3F
> [MATH3D]: Update MATH3D_DistanceBetweenPositions

- KAIN2/Game/MATH3D.C
https://decomp.me/scratch/HfChy
> [MATH3D]: Update MATH3D_AngleBetweenVectors

- KAIN2/Game/MATH3D.C
https://decomp.me/scratch/oZAAg
> [MATH3D]: Update MATH3D_RotationFromPosToPos

- KAIN2/Game/MATH3D.C
https://decomp.me/scratch/SGLSq
> [MATH3D]: Update MATH3D_ElevationFromPosToPos

- KAIN2/Game/MATH3D.C
https://decomp.me/scratch/lCRFj
> [MATH3D]: Update MATH3D_ConeDetect

- KAIN2/Game/MATH3D.C
https://decomp.me/scratch/XVRLn
> [MATH3D]: Update MATH3D_ZYXtoXYZ

- KAIN2/Game/MATH3D.C
https://decomp.me/scratch/wou89
> [MATH3D]: Update MATH3D_SetUnityMatrix

- KAIN2/Game/LOAD3D.C
https://decomp.me/scratch/UGsDw
> [LOAD3D]: Update LOAD_GetBigFileEntryByHash

- KAIN2/Game/LOAD3D.C
https://decomp.me/scratch/zXvwx
> [LOAD3D]: Update LOAD_LoadTIM2

- KAIN2/Game/LOAD3D.C
https://decomp.me/scratch/7RjQ4
> [LOAD3D]: Update LOAD_DoesFileExist

- KAIN2/Game/LOAD3D.C
https://decomp.me/scratch/1iVwi
> [LOAD3D]: Update LOAD_ChangeDirectoryByID

- KAIN2/Game/LOAD3D.C
https://decomp.me/scratch/8b0Ot
> [LOAD3D]: Update LOAD_RelocBinaryData

- KAIN2/Game/LOAD3D.C
https://decomp.me/scratch/akkxJ
> [LOAD3D]: Update LOAD_GetBigFileEntry

- KAIN2/Game/LOAD3D.C
https://decomp.me/scratch/WOo5r
> [LOAD3D]: Update LOAD_NonBlockingReadFile

- KAIN2/Game/LOAD3D.C
https://decomp.me/scratch/f9bzp
> [LOAD3D]: Update LOAD_LoadTIM

- KAIN2/Game/LOAD3D.C
https://decomp.me/scratch/IYk6e
> [LOAD3D]: Update LOAD_CleanUpBuffers

- KAIN2/Game/LOAD3D.C
https://decomp.me/scratch/wEJjL
> [LOAD3D]: Update LOAD_InitBuffers

- KAIN2/Game/LOAD3D.C
https://decomp.me/scratch/87SnU
> [LOAD3D]: Update LOAD_InitCdStreamMode

- KAIN2/Game/LOAD3D.C
https://decomp.me/scratch/6Yzx8
> [LOAD3D]: Update LOAD_DumpCurrentDir

- KAIN2/Game/LOAD3D.C
https://decomp.me/scratch/Pwsgr
> [LOAD3D]: Update LOAD_SetSearchDirectory

- KAIN2/Game/LOAD3D.C
https://decomp.me/scratch/YNm3I
> [LOAD3D]: Update LOAD_GetSearchDirectory

- KAIN2/Game/LOAD3D.C
https://decomp.me/scratch/92iqH
> [LOAD3D]: Update LOAD_ChangeDirectoryFlag

- KAIN2/Game/LOAD3D.C
https://decomp.me/scratch/gTyuz
> [LOAD3D]: Update LOAD_UpdateBigFilePointers

- KAIN2/Game/LOAD3D.C
https://decomp.me/scratch/cFw4T
> [LOAD3D]: Update LOAD_IsFileLoading

- KAIN2/Game/LOAD3D.C
https://decomp.me/scratch/YVz3N
> [LOAD3D]: Update LOAD_StopLoad

- KAIN2/Game/GENERIC.C
https://decomp.me/scratch/Ehu3E
> [GENERIC]: Update GenericRelocateTune

- KAIN2/Game/GENERIC.C
https://decomp.me/scratch/QDodz
> [GENERIC]: Update GenericProcess

- KAIN2/Game/LOAD3D.C
https://decomp.me/scratch/tPtDV
> [LOAD3D]: Update LOAD_CdReadFromBigFile

- KAIN2/Game/LOAD3D.C
https://decomp.me/scratch/Rb5Z7
> [LOAD3D]: Update LOAD_ReadDirectory

- KAIN2/Game/LOAD3D.C
https://decomp.me/scratch/N3JDA
> [LOAD3D]: Update LOAD_CD_ReadPartOfFile

- KAIN2/Game/LOAD3D.C
https://decomp.me/scratch/1FCUw
> [LOAD3D]: Update LOAD_SetupFileInfo

- KAIN2/Game/LOAD3D.C
https://decomp.me/scratch/2RkWk
> [LOAD3D]: Update LOAD_DoCDBufferedReading

- KAIN2/Game/LOAD3D.C
https://decomp.me/scratch/qbMXT
> [LOAD3D]: Update LOAD_UpdateCheckSum

- KAIN2/Game/LOAD3D.C
https://decomp.me/scratch/NQTK9
> [LOAD3D]: Update LOAD_InitCd

- KAIN2/Game/GENERIC.C
https://decomp.me/scratch/HzpMa
> [GENERIC]: Update GenericMessage

- KAIN2/Game/RAZIEL/SENSES.C
https://decomp.me/scratch/MKia7
> [SENSES]: Update UpdateAutoFaceAngle

- KAIN2/Game/RAZIEL/CONTROL.C
https://decomp.me/scratch/MODKg
> [CONTROL]: Update SetExternalTransitionForce

- KAIN2/Game/FX.C
https://decomp.me/scratch/WpZTN
> [FX]: Update FX_EndPassthruFX

- KAIN2/Game/RAZIEL/ALGOCTRL.C
https://decomp.me/scratch/mfrR8
> [ALGOCTRL]: Update DeInitAlgorithmicWings

- KAIN2/Game/RAZIEL/ALGOCTRL.C
https://decomp.me/scratch/s0hYi
> [ALGOCTRL]: Update InitAlgorithmicWings

- KAIN2/Game/GAMELOOP.C
https://decomp.me/scratch/LJMc9
> [GAMELOOP]: Update GAMELOOP_GetGT

- KAIN2/Game/GAMELOOP.C
https://decomp.me/scratch/rjzdq
> [GAMELOOP]: Update GAMELOOP_GetMatrices

- KAIN2/Game/GAMELOOP.C
https://decomp.me/scratch/licJj
> [GAMELOOP]: Update PSX_GameLoop

- KAIN2/Game/GAMELOOP.C
https://decomp.me/scratch/5Oj6h
> [GAMELOOP]: Update GAMELOOP_RequestLevelChange

- KAIN2/Game/GAMELOOP.C
- KAIN2/Game/MATH3D.H
https://decomp.me/scratch/W02fQ
> [GAMELOOP]: Update LoadLevels

- KAIN2/Game/RAZIEL/ATTACK.C
Matching - 99.28%
https://decomp.me/scratch/QyBYv
> [ATTACK]: Update StateHandlerDecodeHold

- KAIN2/Game/RAZIEL/CONTROL.C
https://decomp.me/scratch/eEr3y
> [CONTROL]: Update ProcessPhysics

- KAIN2/Game/RAZIEL/CONTROL.C
https://decomp.me/scratch/mXFIk
> [CONTROL]: Update SetDropPhysics

- KAIN2/Game/RAZIEL/CONTROL.C
https://decomp.me/scratch/qHM7h
> [CONTROL]: Update SetDampingPhysics

- KAIN2/Game/RAZIEL/CONTROL.C
https://decomp.me/scratch/6TLmg
> [CONTROL]: Update SetPhysics

- KAIN2/Game/RAZIEL/CONTROL.C
https://decomp.me/scratch/LPGiQ
> [CONTROL]: Update ResetPhysics

- KAIN2/Game/RELMOD.C
https://decomp.me/scratch/liIFG
> [RELMOD]: Update RELMOD_InitModulePointers

- KAIN2/Game/GENERIC.C
https://decomp.me/scratch/ahZiY
> [GENERIC]: Update GenericInit

- KAIN2/Game/FX.C
Matching - 82.27%
https://decomp.me/scratch/SRJyB
> [FX]: Update FX_Spiral

- KAIN2/Game/STREAM.C
Matching - 78.98%
https://decomp.me/scratch/YnzAX
> [STREAM]: Update DrawFogRectangle

- KAIN2/Game/INSTANCE.C
Matching - 99.77%
https://decomp.me/scratch/ALC6c
> [INSTANCE]: Update INSTANCE_ProcessFunctions

- KAIN2/Game/RAZIEL/STEERING.C
Replaced bit shifts for the actual arithmetic operations employed in the original code.
https://decomp.me/scratch/QjsLM
https://decomp.me/scratch/kObAD
> [STEERING]: Remove bit shifts

- KAIN2/Game/RAZIEL/HEALTH.C
https://decomp.me/scratch/lzA1F
> [HEALTH]: Update InitHealthSystem

- KAIN2/Game/RAZIEL/HEALTH.C
https://decomp.me/scratch/UouCI
> [HEALTH]: Update GainHealth

- KAIN2/Game/RAZIEL/HEALTH.C
https://decomp.me/scratch/VP6Cs
> [HEALTH]: Update BumpUpHealth

- KAIN2/Game/RAZIEL/HEALTH.C
https://decomp.me/scratch/dp2sd
> [HEALTH]: Update GetMaxHealth

- KAIN2/Game/RAZIEL/HEALTH.C
https://decomp.me/scratch/6xuNW
> [HEALTH]: Update ProcessHealth

- KAIN2/Game/RAZIEL/HEALTH.C
https://decomp.me/scratch/eLBsh
> [HEALTH]: Update DrainMana

- KAIN2/Game/RAZIEL/HEALTH.C
https://decomp.me/scratch/VsL1h
> [HEALTH]: Update SetMana

- KAIN2/Game/RAZIEL/HEALTH.C
https://decomp.me/scratch/NK0WJ
> [HEALTH]: Update HealthInstantDeath

- KAIN2/Game/RAZIEL/HEALTH.C
https://decomp.me/scratch/L6cX6
> [HEALTH]: Update RAZIEL_DebugHealthSetScale

- KAIN2/Game/RAZIEL/HEALTH.C
https://decomp.me/scratch/vQqur
> [HEALTH]: Update RAZIEL_DebugManaSetMax

- KAIN2/Game/RAZIEL/HEALTH.C
https://decomp.me/scratch/Oo1nX
> [HEALTH]: Update RAZIEL_DebugManaFillUp

- KAIN2/Game/DEBUG.C
https://decomp.me/scratch/DTI8N
> [DEBUG]: Update DEBUG_UpdateHealth

- KAIN2/Game/RAZIEL/HEALTH.C
https://decomp.me/scratch/fv7Um
> [HEALTH]: Update DrainHealth

- KAIN2/Game/STREAM.C
Matching - 99.57%
https://decomp.me/scratch/8ALJ5
> [STREAM]: Update STREAM_GetClipRect

- KAIN2/Game/GAMELOOP.C
https://decomp.me/scratch/RX14O
> [GAMELOOP]: Update GAMELOOP_ClearGameTracker

- KAIN2/Game/GAMELOOP.C
https://decomp.me/scratch/0xPuz
> [GAMELOOP]: Update GAMELOOP_ResetGameStates

- KAIN2/Game/GAMELOOP.C
https://decomp.me/scratch/PBkjJ
> [GAMELOOP]: Update GAMELOOP_SystemInit

- KAIN2/Game/GAMELOOP.C
https://decomp.me/scratch/a9xGE
> [GAMELOOP]: Update GAMELOOP_AllocStaticMemory

- KAIN2/Game/RAZIEL/RAZIEL.C
https://decomp.me/scratch/q1f0f
> [RAZIEL]: Update SetTimer

- KAIN2/Game/RAZIEL/RAZIEL.C
https://decomp.me/scratch/GIwc7
> [RAZIEL]: Update ProcessSpecialAbilities

- KAIN2/Game/RAZIEL/RAZIEL.C
https://decomp.me/scratch/3Ud77
> [RAZIEL]: Update GetEngageEvent

- KAIN2/Game/RAZIEL/RAZIEL.C
https://decomp.me/scratch/iEgJw
> [RAZIEL]: Update SetupReaction

- KAIN2/Game/RAZIEL/RAZIEL.C
https://decomp.me/scratch/IS0dC
> [RAZIEL]: Update GetControllerMessages

- KAIN2/Game/RAZIEL/RAZIEL.C
https://decomp.me/scratch/xyHFq
> [RAZIEL]: Update EnableWristCollision

- KAIN2/Game/RAZIEL/RAZIEL.C
https://decomp.me/scratch/Lhg2G
> [RAZIEL]: Update DisableWristCollision

- KAIN2/Game/RAZIEL/RAZIEL.C
https://decomp.me/scratch/xq0cP
> [RAZIEL]: Update RazielInit

- KAIN2/Game/RAZIEL/RAZIEL.C
https://decomp.me/scratch/5POnI
> [RAZIEL]: Update RazielProcess

- KAIN2/Game/RAZIEL/RAZIEL.C
https://decomp.me/scratch/bnVxP
> [RAZIEL]: Update mdRazielProcess

- KAIN2/Game/RAZIEL/RAZIEL.C
https://decomp.me/scratch/th2Tf
> [RAZIEL]: Update InitGlyphSystem

- KAIN2/Game/RAZIEL/RAZIEL.C
https://decomp.me/scratch/w75ro
> [RAZIEL]: Update RAZIEL_SetLookAround

- KAIN2/Game/RAZIEL/RAZIEL.C
https://decomp.me/scratch/lZ2MJ
> [RAZIEL]: Update RAZIEL_ResetLookAround

- KAIN2/Game/RAZIEL/CONTROL.C
https://decomp.me/scratch/7AYwY
> [CONTROL]: Update InitExternalForces

- KAIN2/Game/RAZIEL/RAZIEL.C
Matching - 99.97%
https://decomp.me/scratch/Yz63c
> [RAZIEL]: Update InitStates

- KAIN2/Game/RAZIEL/RAZIEL.C
Matching - 96.10%
https://decomp.me/scratch/WwtwW
> [RAZIEL]: Update RazielQuery

- KAIN2/Game/RAZIEL/RAZLIB.C
https://decomp.me/scratch/hbLjx
> [RAZLIB]: Implement razSetCowlNoDraw

- KAIN2/Game/RAZIEL/ATTACK.C
https://decomp.me/scratch/AG4xK
> [ATTACK]: Update StateHandlerAttack2

- KAIN2/Game/GAMELOOP.C
Matching - 99.59%
https://decomp.me/scratch/01SoZ
> [GAMELOOP]: Update GAMELOOP_SetGameTime

- KAIN2/Game/GAMELOOP.C
https://decomp.me/scratch/3uEaC
> [GAMELOOP]: Update GAMELOOP_CalcGameTime

- KAIN2/Game/GAMELOOP.C
https://decomp.me/scratch/SWZ9y
> [GAMELOOP]: Update GAMELOOP_GetTimeOfDay

- KAIN2/Game/GAMELOOP.C
https://decomp.me/scratch/QqSVp
> [GAMELOOP]: Update GAMELOOP_WaitForLoad

- KAIN2/Game/GAMELOOP.C
Matching - 95%
https://decomp.me/scratch/8Gscm
> [GAMELOOP]: Update GAMELOOP_InitStandardObjects

- KAIN2/Game/GAMELOOP.C
https://decomp.me/scratch/zL9W8
> [GAMELOOP]: Update GAMELOOP_LevelLoadAndInit

- KAIN2/Game/GAMELOOP.C
https://decomp.me/scratch/ijUOi
> [GAMELOOP]: Update GAMELOOP_StreamLevelLoadAndInit

- KAIN2/Game/GAMELOOP.C
https://decomp.me/scratch/kCp18
> [GAMELOOP]: Update GAMELOOP_SetScreenWipe

- KAIN2/Game/RAZIEL/RAZIEL.C
https://decomp.me/scratch/3quMg
> [RAZIEL]: Update RAZIEL_TurnHead

- KAIN2/Game/GAMELOOP.C
https://decomp.me/scratch/KnGFA
> [GAMELOOP]: Update UpdateFogSettings

- KAIN2/Game/GAMELOOP.C
https://decomp.me/scratch/X3i3b
> [GAMELOOP]: Update CheckForNoBlend

- KAIN2/Game/GAMELOOP.C
https://decomp.me/scratch/Xa9F5
> [GAMELOOP]: Update BlendToColor

- KAIN2/Game/RAZIEL/RAZIEL.C
https://decomp.me/scratch/6hyw1
> [RAZIEL]: Update StateInitIdle

- KAIN2/Game/RAZIEL/CONTROL.C
- KAIN2/Game/RAZIEL/CONTROL.H
https://decomp.me/scratch/oixvB
> [RAZIEL]: Update SetExternalForce

- KAIN2/Game/RAZIEL/RAZIEL.C
https://decomp.me/scratch/4Xny5
> [RAZIEL]: Update StateHandlerCrouch

- KAIN2/Game/LOAD3D.C
- KAIN2/Game/LOAD3D.H
https://decomp.me/scratch/lXgD4
> [LOAD3D]: Update LOAD_ProcessReadQueue

- KAIN2/Game/LOAD3D.C
https://decomp.me/scratch/AligR
> [LOAD3D]: Update LOAD_CdSeekCallback

- KAIN2/Game/LOAD3D.C
- KAIN2/Game/LOAD3D.H
https://decomp.me/scratch/2PEKf
> [LOAD3D]: Update LOAD_DoCDReading

- KAIN2/Game/RAZIEL/RAZIEL.C
https://decomp.me/scratch/NcFzW
> [RAZIEL]: Update StateInitStartMove

- KAIN2/Game/RAZIEL/RAZIEL.C
https://decomp.me/scratch/4Pp1y
> [RAZIEL]: Update StateInitMove

- KAIN2/Game/RAZIEL/RAZLIB.C
https://decomp.me/scratch/SLzH1
> [RAZLIB]: Update razAlignYRotInterp

- KAIN2/Game/RAZIEL/RAZLIB.C
https://decomp.me/scratch/2jjiM
> [RAZLIB]: Update razSetFadeEffect

- KAIN2/Game/RAZIEL/RAZLIB.C
https://decomp.me/scratch/bGUKm
> [RAZLIB]: Update razPlaneShift

- KAIN2/Game/RAZIEL/RAZLIB.C
https://decomp.me/scratch/83SGg
> [RAZLIB]: Update razSpectralShift

- KAIN2/Game/RAZIEL/RAZLIB.C
https://decomp.me/scratch/R4YpX
> [RAZLIB]: Update razMaterialShift

- KAIN2/Game/RAZIEL/RAZIEL.C
https://decomp.me/scratch/JXBMG
> [RAZIEL]: Update StateHandlerSlide

- KAIN2/Game/RAZIEL/RAZIEL.C
https://decomp.me/scratch/JU66u
> [RAZIEL]: Update StateHandlerDeCompression

- KAIN2/Game/CAMERA.C
Matching - 99.68%
https://decomp.me/scratch/dctSf
> [CAMERA]: Update CAMERA_SetMode

- KAIN2/Game/RAZIEL/RAZIEL.C
Matching - 99.94%
https://decomp.me/scratch/C8Ajm
> [RAZIEL]: Update StateHandlerGlide

- KAIN2/Game/RAZIEL/RAZIEL.C
https://decomp.me/scratch/C8Ajm
> [RAZIEL]: Update ProcessHints

- KAIN2/Game/RAZIEL/RAZIEL.C
https://decomp.me/scratch/UghEH
> [RAZIEL]: Update ProcessInteractiveMusic

- KAIN2/Game/MEMPACK.C
https://decomp.me/scratch/rdiw8
> [MEMPACK]: Update MEMPACK_RelocateCDMemory

- KAIN2/Game/RAZIEL/RAZIEL.C
https://decomp.me/scratch/kdlL1
> [RAZIEL]: Update ProcessEffects

- KAIN2/Game/MEMPACK.C
https://decomp.me/scratch/ki6Ah
> [MEMPACK]: Update MEMPACK_FreeByType

- KAIN2/Game/MEMPACK.C
https://decomp.me/scratch/LOMW0
> [MEMPACK]: Update MEMPACK_ReportFreeMemory

- KAIN2/Game/MEMPACK.C
https://decomp.me/scratch/vgJrp
> [MEMPACK]: Update MEMPACK_ReportMemory2

- KAIN2/Game/MEMPACK.C
https://decomp.me/scratch/OPKJP
> [MEMPACK]: Update MEMPACK_ReportMemory

- KAIN2/Game/MEMPACK.C
https://decomp.me/scratch/8bC9S
> [MEMPACK]: Update MEMPACK_GarbageCollectMalloc

- KAIN2/Game/MEMPACK.C
https://decomp.me/scratch/eApsh
> [MEMPACK]: Update MEMPACK_GarbageCollectFree

- KAIN2/Game/MEMPACK.C
https://decomp.me/scratch/CLjAB
> [MEMPACK]: Update MEMPACK_DoGarbageCollection

- KAIN2/Game/RAZIEL/RAZIEL.C
https://decomp.me/scratch/7mvdO
> [RAZIEL]: Update StateHandlerGlyphs

- KAIN2/Game/MEMPACK.C
https://decomp.me/scratch/0Jpbl
> [MEMPACK]: Update MEMPACK_Free

- KAIN2/Game/MEMPACK.C
https://decomp.me/scratch/WzwD2
> [MEMPACK]: Update MEMPACK_Return

- KAIN2/Game/MEMPACK.C
https://decomp.me/scratch/GRORj
> [MEMPACK]: Update MEMPACK_Malloc

- KAIN2/Game/MEMPACK.C
https://decomp.me/scratch/Zj5ss
> [MEMPACK]: Update MEMPACK_RelocatableType

- KAIN2/Game/MEMPACK.C
https://decomp.me/scratch/8wtXc
> [MEMPACK]: Update MEMPACK_Init

- KAIN2/Game/FX.C
https://decomp.me/scratch/TLiha
> [FX]: Fix web build

- KAIN2/Game/COLLIDE.C
Matching - 58.73%
https://decomp.me/scratch/ToyWH
> [COLLIDE]: Update COLLIDE_MakeNormal

- KAIN2/Game/GAMEPAD.C
https://decomp.me/scratch/Mj37a
> [GAMEPAD]: Update GAMEPAD_Process

- KAIN2/Game/GAMELOOP.C
Matching - 98.15%
https://decomp.me/scratch/1de0C
> [GAMELOOP]: Update GAMELOOP_ModeStartRunning

- KAIN2/Game/GAMELOOP.C
Matching - 98.89%
https://decomp.me/scratch/feMMg
> [GAMELOOP]: Update GAMELOOP_ModeStartPause

- KAIN2/Game/RAZIEL/RAZLIB.C
https://decomp.me/scratch/hbLjx
> [RAZLIB]: Update razSetCowlNoDraw

- KAIN2/Game/EVENT.C
https://decomp.me/scratch/emZBD
> [EVENT]: Update EVENT_DoCameraAction

- KAIN2/Game/MONSTER/MONSENSE.C
https://decomp.me/scratch/KaHRj
> [MONSENSE]: Update MONSENSE_DoSenses

- KAIN2/Game/GAMELOOP.C
Matching - 99.74%
https://decomp.me/scratch/b9vWy
> [GAMELOOP]: Update GAMELOOP_ChangeMode

- KAIN2/Game/GAMELOOP.C
https://decomp.me/scratch/ehlVS
> [GAMELOOP]: Update GAMELOOP_GetMainRenderUnit

- KAIN2/Game/GAMELOOP.C
https://decomp.me/scratch/dh80s
> [GAMELOOP]: Update Switch_For_Redraw

- KAIN2/Game/GAMELOOP.C
https://decomp.me/scratch/YDiA0
> [GAMELOOP]: Update GAMELOOP_Set_Pause_Redraw

- KAIN2/Game/GAMELOOP.C
https://decomp.me/scratch/rLacJ
> [GAMELOOP]: Update ResetDrawPage

- KAIN2/Game/GAMELOOP.C
https://decomp.me/scratch/NDXY9
> [GAMELOOP]: Update GAMELOOP_Set24FPS

- KAIN2/Game/GAMELOOP.C
https://decomp.me/scratch/8mim8
> [GAMELOOP]: Update GAMELOOP_Reset24FPS

- KAIN2/Game/GAMELOOP.C
https://decomp.me/scratch/mqG3n
> [GAMELOOP]: Update GAMELOOP_SetupRenderFunction

- KAIN2/Game/GAMELOOP.C
https://decomp.me/scratch/3jxx6
> [GAMELOOP]: Update GAMELOOP_SwitchTheDrawBuffer

- KAIN2/Game/GAMEPAD.C
https://decomp.me/scratch/NiSej
> [GAMELOOP]: Update GAMEPAD_DisplayControllerStatus

- KAIN2/Game/GAMELOOP.C
- KAIN2/Game/GAMELOOP.H
https://decomp.me/scratch/KycFO
> [GAMELOOP]: Update GAMELOOP_Process

- KAIN2/Game/GAMELOOP.C
- KAIN2/Game/GAMELOOP.H
Fix STACK_RESTORE macro requirements.
> [GAMELOOP]: Fix macro

- KAIN2/Game/GAMEPAD.C
https://decomp.me/scratch/rzB6v
> [GAMEPAD]: Update GAMEPAD_GetData

- KAIN2/Game/GAMEPAD.C
https://decomp.me/scratch/GO8jw
> [GAMEPAD]: Update GAMEPAD_DetectInit

- KAIN2/Game/GAMEPAD.C
https://decomp.me/scratch/sS1xZ
> [GAMEPAD]: Update PSXPAD_TranslateData

- KAIN2/Game/MONSTER/SOUL.C
https://decomp.me/scratch/FfkwB
> [SOUL]: Update SOUL_FleeEntry

- KAIN2/Game/MONSTER/SOUL.C
https://decomp.me/scratch/jFUYH
> [SOUL]: Update SOUL_CalcAccel

- KAIN2/Game/MONSTER/SOUL.C
https://decomp.me/scratch/dr81e
> [SOUL]: Update SOUL_SoulSuckEntry

- KAIN2/Game/MONSTER/SOUL.C
https://decomp.me/scratch/txUmh
> [SOUL]: Update SOUL_CleanUp

- KAIN2/Game/GAMELOOP.C
Matching - 90.22%
https://decomp.me/scratch/LOjfE
> [GAMELOOP]: Update StreamRenderLevel

- KAIN2/Game/GAMELOOP.C
https://decomp.me/scratch/7088b
> [GAMELOOP]: Update StreamIntroInstancesForUnit

- KAIN2/Game/CAMERA.C
https://decomp.me/scratch/fE0wE
> [CAMERA]: Update CAMERA_RestoreMode

- KAIN2/Game/SOUND.C
https://decomp.me/scratch/iX8Pr
> [SOUND]: Update SOUND_ResetMusicModifier

- KAIN2/Game/SOUND.C
https://decomp.me/scratch/PfKvv
> [SOUND]: Update SOUND_SetMusicModifier

- KAIN2/Game/SOUND.C
https://decomp.me/scratch/da5Ko
> [SOUND]: Update SOUND_ShutdownMusic

- KAIN2/Game/SOUND.C
https://decomp.me/scratch/7R2AN
> [SOUND]: Update SOUND_PlaneShift

- KAIN2/Game/MATH3D.C
Matching - 96.81%
https://decomp.me/scratch/1JK4A
> [MATH3D]: Update MATH3D_FastSqrt0

- KAIN2/Game/MATH3D.C
Matching - 67.49%
https://decomp.me/scratch/78Sed
> [MATH3D]: Update AngleMoveToward

- KAIN2/Game/INSTANCE.C
https://decomp.me/scratch/4fEsV
> [INSTANCE]: Update INSTANCE_ProcessIntro

- KAIN2/Game/PSX/COLLIDES.C
- KAIN2/Game/PSX/COLLIDES.H
https://decomp.me/scratch/iChf9
> [COLLIDES]: Implement BSP_SphereIntersectsViewVolume_S

- KAIN2/Game/GAMELOOP.C
Matching - 95.19%
https://decomp.me/scratch/oTwGz
> [GAMELOOP]: Update MainRenderLevel

- KAIN2/Game/G2/TIMERG2.C
https://decomp.me/scratch/0UyHY
> [TIMERG2]: Update G2Timer_GetFrameTime

- KAIN2/Game/G2/QUATG2.C
https://decomp.me/scratch/Nb20c
> [QUATG2]: Update G2Quat_ToEuler

- KAIN2/Game/G2/POOLMMG2.C
https://decomp.me/scratch/kikvX
> [POOLMMG2]: Update G2PoolMem_Free

- KAIN2/Game/G2/MAING2.C
https://decomp.me/scratch/yf7ja
> [MAING2]: Update MainG2_InitEngine

- KAIN2/Game/DEBUG.C
Replaced wrong value for proper one.
> [DEBUG]: fogMenu fix

- KAIN2/Game/RAZIEL/RAZIEL.C
https://decomp.me/scratch/uhY8c
> [RAZIEL]: Update RAZIEL_OkToLookAround

- KAIN2/Game/G2/ANMG2ILF.H
- KAIN2/Game/GLYPH.H
- KAIN2/Game/MCARD/MEMCARD.H
- KAIN2/Game/MENU/MENU.H
- KAIN2/Game/MONSTER/HUMAN.C
- KAIN2/Game/MONSTER/MONSTER.H
- KAIN2/Game/PSX/AADLIB.H
- KAIN2/Game/STATE.H
Remove auto-generated function pointers that aren't being currently used.
> Remove unused function pointers

- KAIN2/Game/CAMERA.C
https://decomp.me/scratch/XnyhK
> [CAMERA]: Update CAMERA_AbsoluteCollision

- KAIN2/Game/G2/INSTNCG2.C
https://decomp.me/scratch/3ARbf
> [INSTNCG2]: Update _G2Instance_BuildNonAnimatedTransforms

- KAIN2/Game/G2/INSTNCG2.C
https://decomp.me/scratch/GPvLq
> [INSTNCG2]: Update _G2Instance_BuildDeactivatedTransforms

- KAIN2/Game/FX.C
https://decomp.me/scratch/v7ZQP
> [FX]: Update FX_MakeSoulDust

- KAIN2/Game/CAMERA.C
https://decomp.me/scratch/2HncK
> [CAMERA]: Update CAMERA_dampgetline

- KAIN2/Game/RAZIEL/RAZLIB.C
https://decomp.me/scratch/ZreFJ
> [RAZLIB]: Update razLaunchForce

- KAIN2/Game/VRAM.C
- KAIN2/Game/VRAM.H
Matching - 99.44%
https://decomp.me/scratch/I8wkA
> [VRAM]: Update VRAM_InsertFreeVram

- KAIN2/Game/CAMERA.C
https://decomp.me/scratch/ri8N6
> [CAMERA]: Update CAMERA_SphereToSphereWithLines

- KAIN2/Game/SOUND.C
https://decomp.me/scratch/8ErHv
> [SOUND]: Update SOUND_UpdateSound

- KAIN2/Game/CAMERA.C
https://decomp.me/scratch/3CHzO
> [CAMERA]: Update CAMERA_SetupColInfo

- KAIN2/Game/CAMERA.C
https://decomp.me/scratch/MTcN7
> [CAMERA]: Update CAMERA_LookProcess

- KAIN2/Game/BSP.C
- KAIN2/Game/COLLIDE.C
- KAIN2/Game/PSX/COLLIDES.C
- KAIN2/Game/PSX/COLLIDES.H
https://decomp.me/scratch/miMDA
> [COLLIDES]: Update COLLIDE_NearestPointOnPlane_S

- KAIN2/Game/SOUND.C
https://decomp.me/scratch/G5vy2
> [SOUND]: Update SOUND_ProcessMusicLoad

- KAIN2/Game/CAMERA.C
Removed inline functions that weren't getting used.
> [CAMERA]: Remove unused inlines

- KAIN2/Game/CAMERA.C
https://decomp.me/scratch/GHx0Y
> [CAMERA]: Update CAMERA_Adjust

- KAIN2/Game/CAMERA.C
- KAIN2/Game/MATH3D.H
https://decomp.me/scratch/BarDY
> [CAMERA]: Update CAMERA_CinematicProcess

- KAIN2/Game/CAMERA.C
Matching - 99.81%
https://decomp.me/scratch/ztZvU
> [CAMERA]: Update CAMERA_ACForcedMovement

- KAIN2/Game/CAMERA.C
Matching - 99.81%
https://decomp.me/scratch/6r8TY
> [CAMERA]: Update CAMERA_DoPanicCheck

- KAIN2/Game/PSX/COLLIDES.C
- KAIN2/Game/PSX/COLLIDES.H
https://decomp.me/scratch/i785X
> [COLLIDES]: Update MATH3D_racos_S

- KAIN2/Game/GAMELOOP.C
Matching - 99.84%
https://decomp.me/scratch/DZUq0
> [GAMELOOP]: Update GAMELOOP_DoTimeProcess

- KAIN2/Game/PIPE3D.C
https://decomp.me/scratch/msx4U
> [PIPE3D]: Update PIPE3D_AnimateTextures

- KAIN2/Game/PHYSOBS.C
Updated code of certain functions to make them more easily readable.
> [PHYSOBS]: Update code

- KAIN2/Game/G2/INSTNCG2.C
https://decomp.me/scratch/8L8OZ
> [INSTNCG2]: Update _G2Instance_RebuildNonAnimatedTransforms

- KAIN2/Game/CAMERA.C
Matching - 94.44%
https://decomp.me/scratch/IL3Sk
> [CAMERA]: Update CAMERA_CalcVVClipInfo

- KAIN2/Game/CAMERA.C
https://decomp.me/scratch/jPOav
> [CAMERA]: Update CAMERA_SetViewVolume

- KAIN2/Game/DRAW.C
https://decomp.me/scratch/KyIKs
> [DRAW]: Update DRAW_InitShadow

- KAIN2/Game/CAMERA.C
https://decomp.me/scratch/fTJNn
> [CAMERA]: Update CAMERA_SetProjDistance

- KAIN2/Game/CAMERA.C
https://decomp.me/scratch/dVsSe
> [CAMERA]: Update CAMERA_SaveMode

- KAIN2/Game/CAMERA.C
https://decomp.me/scratch/t1hZC
> [CAMERA]: Update SplineGetNextPointDC

- KAIN2/Game/RAZIEL/RAZIEL.C
Matching - 99.28%
https://decomp.me/scratch/mACka
> [RAZIEL]: Update RazielAdditionalCollide

- KAIN2/Game/CAMERA.H
Updated structs to the current game version.
> [CAMERA]: Update structs

- KAIN2/Game/G2/INSTNCG2.C
https://decomp.me/scratch/SMzRn
> [INSTNCG2]: Update G2Instance_BuildTransformsForList

- KAIN2/Game/G2/QUATG2.H
Remove this commented out code.
> [QUATG2]: Delete unused code

- KAIN2/Game/G2/MAING2.H
Update structs to the current game version.
> [MAING2]: Update structs
